// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/(app)/(dashboard)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(app)/(dashboard)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/admin/access/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/access">> = Specific
  const handler = {} as typeof import("../../../app/(app)/admin/access/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/admin/assets/[assetId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/assets/[assetId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/admin/assets/[assetId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/admin/assets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/assets">> = Specific
  const handler = {} as typeof import("../../../app/(app)/admin/assets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/admin/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/audit">> = Specific
  const handler = {} as typeof import("../../../app/(app)/admin/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/admin/company/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/company">> = Specific
  const handler = {} as typeof import("../../../app/(app)/admin/company/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/admin/couriers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/couriers">> = Specific
  const handler = {} as typeof import("../../../app/(app)/admin/couriers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/admin/divisions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/divisions">> = Specific
  const handler = {} as typeof import("../../../app/(app)/admin/divisions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/admin/document-no-formats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/document-no-formats">> = Specific
  const handler = {} as typeof import("../../../app/(app)/admin/document-no-formats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/admin/organisation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/organisation">> = Specific
  const handler = {} as typeof import("../../../app/(app)/admin/organisation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/(app)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/admin/resources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/resources">> = Specific
  const handler = {} as typeof import("../../../app/(app)/admin/resources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/admin/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/roles">> = Specific
  const handler = {} as typeof import("../../../app/(app)/admin/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../../app/(app)/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../../app/(app)/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/finance/accounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/accounts">> = Specific
  const handler = {} as typeof import("../../../app/(app)/finance/accounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/finance/ar-ap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/ar-ap">> = Specific
  const handler = {} as typeof import("../../../app/(app)/finance/ar-ap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/finance/bank-journals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/bank-journals">> = Specific
  const handler = {} as typeof import("../../../app/(app)/finance/bank-journals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/finance/bank-limits/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/bank-limits">> = Specific
  const handler = {} as typeof import("../../../app/(app)/finance/bank-limits/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/finance/banking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/banking">> = Specific
  const handler = {} as typeof import("../../../app/(app)/finance/banking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/finance/cheques/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/cheques">> = Specific
  const handler = {} as typeof import("../../../app/(app)/finance/cheques/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/finance/cost-centres/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/cost-centres">> = Specific
  const handler = {} as typeof import("../../../app/(app)/finance/cost-centres/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/finance/cost-heads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/cost-heads">> = Specific
  const handler = {} as typeof import("../../../app/(app)/finance/cost-heads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/finance/domestic-invoices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/domestic-invoices">> = Specific
  const handler = {} as typeof import("../../../app/(app)/finance/domestic-invoices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/finance/exchange-rates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/exchange-rates">> = Specific
  const handler = {} as typeof import("../../../app/(app)/finance/exchange-rates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/finance/forward-contracts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/forward-contracts">> = Specific
  const handler = {} as typeof import("../../../app/(app)/finance/forward-contracts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/finance/invoicing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/invoicing">> = Specific
  const handler = {} as typeof import("../../../app/(app)/finance/invoicing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/finance/ledger/[entryId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/ledger/[entryId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/finance/ledger/[entryId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/finance/ledger/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/ledger">> = Specific
  const handler = {} as typeof import("../../../app/(app)/finance/ledger/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/finance/notes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/notes">> = Specific
  const handler = {} as typeof import("../../../app/(app)/finance/notes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/finance/other-entries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/other-entries">> = Specific
  const handler = {} as typeof import("../../../app/(app)/finance/other-entries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance">> = Specific
  const handler = {} as typeof import("../../../app/(app)/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/finance/party-openings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/party-openings">> = Specific
  const handler = {} as typeof import("../../../app/(app)/finance/party-openings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/finance/payables/[payableId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/payables/[payableId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/finance/payables/[payableId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/finance/payables/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/payables">> = Specific
  const handler = {} as typeof import("../../../app/(app)/finance/payables/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/finance/pnl/[shipmentId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/pnl/[shipmentId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/finance/pnl/[shipmentId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/finance/pnl/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/pnl">> = Specific
  const handler = {} as typeof import("../../../app/(app)/finance/pnl/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/finance/provisional-invoices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/provisional-invoices">> = Specific
  const handler = {} as typeof import("../../../app/(app)/finance/provisional-invoices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/finance/receivables/[receivableId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/receivables/[receivableId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/finance/receivables/[receivableId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/finance/receivables/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/receivables">> = Specific
  const handler = {} as typeof import("../../../app/(app)/finance/receivables/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/finance/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/results">> = Specific
  const handler = {} as typeof import("../../../app/(app)/finance/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/finance/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/setup">> = Specific
  const handler = {} as typeof import("../../../app/(app)/finance/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/hr/adjustments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/adjustments">> = Specific
  const handler = {} as typeof import("../../../app/(app)/hr/adjustments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/hr/advances/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/advances">> = Specific
  const handler = {} as typeof import("../../../app/(app)/hr/advances/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/hr/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/attendance">> = Specific
  const handler = {} as typeof import("../../../app/(app)/hr/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/hr/comp-events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/comp-events">> = Specific
  const handler = {} as typeof import("../../../app/(app)/hr/comp-events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/hr/compliance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/compliance">> = Specific
  const handler = {} as typeof import("../../../app/(app)/hr/compliance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/hr/contractors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/contractors">> = Specific
  const handler = {} as typeof import("../../../app/(app)/hr/contractors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/hr/leave/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/leave">> = Specific
  const handler = {} as typeof import("../../../app/(app)/hr/leave/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/hr/lifecycle/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/lifecycle">> = Specific
  const handler = {} as typeof import("../../../app/(app)/hr/lifecycle/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/hr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr">> = Specific
  const handler = {} as typeof import("../../../app/(app)/hr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/hr/pay/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/pay">> = Specific
  const handler = {} as typeof import("../../../app/(app)/hr/pay/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/hr/payroll/[runId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/payroll/[runId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/hr/payroll/[runId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/hr/payroll/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/payroll">> = Specific
  const handler = {} as typeof import("../../../app/(app)/hr/payroll/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/hr/payslip/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/payslip">> = Specific
  const handler = {} as typeof import("../../../app/(app)/hr/payslip/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/hr/people/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/people">> = Specific
  const handler = {} as typeof import("../../../app/(app)/hr/people/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/hr/piece-records/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/piece-records">> = Specific
  const handler = {} as typeof import("../../../app/(app)/hr/piece-records/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/hr/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/settings">> = Specific
  const handler = {} as typeof import("../../../app/(app)/hr/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/hr/staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/staff">> = Specific
  const handler = {} as typeof import("../../../app/(app)/hr/staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/hr/statutory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/statutory">> = Specific
  const handler = {} as typeof import("../../../app/(app)/hr/statutory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/hr/time/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/time">> = Specific
  const handler = {} as typeof import("../../../app/(app)/hr/time/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/hr/workers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/workers">> = Specific
  const handler = {} as typeof import("../../../app/(app)/hr/workers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/integration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/integration">> = Specific
  const handler = {} as typeof import("../../../app/(app)/integration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/integration/tally/[exportId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/integration/tally/[exportId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/integration/tally/[exportId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/integration/tally/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/integration/tally">> = Specific
  const handler = {} as typeof import("../../../app/(app)/integration/tally/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/logistics/[shipmentId]/documents/[docType]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistics/[shipmentId]/documents/[docType]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/logistics/[shipmentId]/documents/[docType]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/logistics/[shipmentId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistics/[shipmentId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/logistics/[shipmentId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/logistics/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistics/categories">> = Specific
  const handler = {} as typeof import("../../../app/(app)/logistics/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/logistics/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistics/documents">> = Specific
  const handler = {} as typeof import("../../../app/(app)/logistics/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/logistics/epcg/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistics/epcg">> = Specific
  const handler = {} as typeof import("../../../app/(app)/logistics/epcg/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/logistics/export-categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistics/export-categories">> = Specific
  const handler = {} as typeof import("../../../app/(app)/logistics/export-categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/logistics/exports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistics/exports">> = Specific
  const handler = {} as typeof import("../../../app/(app)/logistics/exports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/logistics/incentives/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistics/incentives">> = Specific
  const handler = {} as typeof import("../../../app/(app)/logistics/incentives/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/logistics/lc/[lcId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistics/lc/[lcId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/logistics/lc/[lcId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/logistics/lc/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistics/lc">> = Specific
  const handler = {} as typeof import("../../../app/(app)/logistics/lc/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/logistics/order-categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistics/order-categories">> = Specific
  const handler = {} as typeof import("../../../app/(app)/logistics/order-categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/logistics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistics">> = Specific
  const handler = {} as typeof import("../../../app/(app)/logistics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/logistics/proforma/[proformaId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistics/proforma/[proformaId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/logistics/proforma/[proformaId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/logistics/proforma/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistics/proforma">> = Specific
  const handler = {} as typeof import("../../../app/(app)/logistics/proforma/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/masters/[submodule]/[entity]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/masters/[submodule]/[entity]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/masters/[submodule]/[entity]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/masters/[submodule]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/masters/[submodule]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/masters/[submodule]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/masters/materials/[entity]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/masters/materials/[entity]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/masters/materials/[entity]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/masters/materials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/masters/materials">> = Specific
  const handler = {} as typeof import("../../../app/(app)/masters/materials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/masters/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/masters">> = Specific
  const handler = {} as typeof import("../../../app/(app)/masters/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/[orderId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/[orderId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/[orderId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/[orderId]/processes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/[orderId]/processes">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/[orderId]/processes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/advised-items/[orderId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/advised-items/[orderId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/advised-items/[orderId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/advised-items/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/advised-items">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/advised-items/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/all/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/all">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/all/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/amendments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/amendments">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/amendments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/approve-amendments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/approve-amendments">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/approve-amendments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/budget-approval/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/budget-approval">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/budget-approval/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/budgets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/budgets">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/budgets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/cancellations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/cancellations">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/cancellations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/changes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/changes">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/changes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/closure/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/closure">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/closure/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/completions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/completions">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/completions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/confirmations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/confirmations">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/confirmations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/contract-review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/contract-review">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/contract-review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/due-date-confirmations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/due-date-confirmations">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/due-date-confirmations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/excess-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/excess-orders">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/excess-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/execution/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/execution">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/execution/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/fabric-bom/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/fabric-bom">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/fabric-bom/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/fabric-plan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/fabric-plan">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/fabric-plan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/garment-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/garment-orders">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/garment-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/garment-processes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/garment-processes">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/garment-processes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/internal-work-orders/[iwoId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/internal-work-orders/[iwoId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/internal-work-orders/[iwoId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/internal-work-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/internal-work-orders">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/internal-work-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/material-bom-amendment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/material-bom-amendment">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/material-bom-amendment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/material-bom/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/material-bom">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/material-bom/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/order-booking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/order-booking">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/order-booking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/pack-ratios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/pack-ratios">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/pack-ratios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/packing-advice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/packing-advice">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/packing-advice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/price-confirmation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/price-confirmation">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/price-confirmation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/process-amendments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/process-amendments">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/process-amendments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/retired/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/retired">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/retired/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/setup">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/styles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/styles">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/styles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/ta-completion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/ta-completion">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/ta-completion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/ta-department-assign/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/ta-department-assign">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/ta-department-assign/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/ta-masters/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/ta-masters">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/ta-masters/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/ta-plan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/ta-plan">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/ta-plan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/ta-style/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/ta-style">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/ta-style/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/ta-user-rights/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/ta-user-rights">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/ta-user-rights/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/orders/ta/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/ta">> = Specific
  const handler = {} as typeof import("../../../app/(app)/orders/ta/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/accessory-bom/[bomId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/accessory-bom/[bomId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/accessory-bom/[bomId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/accessory-bom/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/accessory-bom">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/accessory-bom/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/bom-shortage/[shortageId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/bom-shortage/[shortageId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/bom-shortage/[shortageId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/bom-shortage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/bom-shortage">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/bom-shortage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/bom-transfer/[transferId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/bom-transfer/[transferId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/bom-transfer/[transferId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/bom-transfer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/bom-transfer">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/bom-transfer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/bom/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/bom">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/bom/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/budgets/[budgetId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/budgets/[budgetId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/budgets/[budgetId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/budgets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/budgets">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/budgets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/capacity-planning/[planId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/capacity-planning/[planId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/capacity-planning/[planId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/capacity-planning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/capacity-planning">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/capacity-planning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/capacity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/capacity">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/capacity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/excess-order/[orderId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/excess-order/[orderId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/excess-order/[orderId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/excess-order/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/excess-order">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/excess-order/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/fabric-bom/[bomId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/fabric-bom/[bomId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/fabric-bom/[bomId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/fabric-bom/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/fabric-bom">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/fabric-bom/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/fabric-consumption/[consumptionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/fabric-consumption/[consumptionId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/fabric-consumption/[consumptionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/fabric-consumption/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/fabric-consumption">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/fabric-consumption/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/fabric-order/[orderId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/fabric-order/[orderId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/fabric-order/[orderId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/fabric-order/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/fabric-order">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/fabric-order/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/fabric/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/fabric">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/fabric/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/garment-bom/[bomId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/garment-bom/[bomId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/garment-bom/[bomId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/garment-bom/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/garment-bom">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/garment-bom/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/garment-ppm-cancel/[cancelId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/garment-ppm-cancel/[cancelId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/garment-ppm-cancel/[cancelId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/garment-ppm-cancel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/garment-ppm-cancel">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/garment-ppm-cancel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/garment-ppm/[ppmId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/garment-ppm/[ppmId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/garment-ppm/[ppmId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/garment-ppm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/garment-ppm">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/garment-ppm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/material-bom/[bomId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/material-bom/[bomId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/material-bom/[bomId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/material-bom/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/material-bom">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/material-bom/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/material-excess-plan/[planId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/material-excess-plan/[planId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/material-excess-plan/[planId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/material-excess-plan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/material-excess-plan">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/material-excess-plan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/material-rate/[rateId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/material-rate/[rateId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/material-rate/[rateId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/material-rate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/material-rate">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/material-rate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/material/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/material">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/material/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/ppm-cancel/[cancelId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/ppm-cancel/[cancelId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/ppm-cancel/[cancelId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/ppm-cancel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/ppm-cancel">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/ppm-cancel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/ppm-completion/[completionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/ppm-completion/[completionId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/ppm-completion/[completionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/ppm-completion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/ppm-completion">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/ppm-completion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/ppm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/ppm">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/ppm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/processing-ppm/[ppmId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/processing-ppm/[ppmId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/processing-ppm/[ppmId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/processing-ppm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/processing-ppm">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/processing-ppm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/production-planning/[planId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/production-planning/[planId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/production-planning/[planId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/production-planning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/production-planning">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/production-planning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/purchase-ppm/[ppmId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/purchase-ppm/[ppmId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/purchase-ppm/[ppmId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/planning/purchase-ppm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning/purchase-ppm">> = Specific
  const handler = {} as typeof import("../../../app/(app)/planning/purchase-ppm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/production/despatch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/production/despatch">> = Specific
  const handler = {} as typeof import("../../../app/(app)/production/despatch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/production/finishing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/production/finishing">> = Specific
  const handler = {} as typeof import("../../../app/(app)/production/finishing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/production/inspections/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/production/inspections">> = Specific
  const handler = {} as typeof import("../../../app/(app)/production/inspections/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/production/job-orders/[jobId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/production/job-orders/[jobId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/production/job-orders/[jobId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/production/job-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/production/job-orders">> = Specific
  const handler = {} as typeof import("../../../app/(app)/production/job-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/production/manufacturing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/production/manufacturing">> = Specific
  const handler = {} as typeof import("../../../app/(app)/production/manufacturing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/production/masters/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/production/masters">> = Specific
  const handler = {} as typeof import("../../../app/(app)/production/masters/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/production/packing-lists/[packingId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/production/packing-lists/[packingId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/production/packing-lists/[packingId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/production/packing-lists/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/production/packing-lists">> = Specific
  const handler = {} as typeof import("../../../app/(app)/production/packing-lists/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/production/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/production">> = Specific
  const handler = {} as typeof import("../../../app/(app)/production/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/production/piece-rates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/production/piece-rates">> = Specific
  const handler = {} as typeof import("../../../app/(app)/production/piece-rates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/purchase/approvals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/approvals">> = Specific
  const handler = {} as typeof import("../../../app/(app)/purchase/approvals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/purchase/completions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/completions">> = Specific
  const handler = {} as typeof import("../../../app/(app)/purchase/completions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/purchase/dc/[dcId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/dc/[dcId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/purchase/dc/[dcId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/purchase/dc/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/dc/new">> = Specific
  const handler = {} as typeof import("../../../app/(app)/purchase/dc/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/purchase/dc/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/dc">> = Specific
  const handler = {} as typeof import("../../../app/(app)/purchase/dc/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/purchase/grn/[grnId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/grn/[grnId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/purchase/grn/[grnId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/purchase/grn/[grnId]/quality/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/grn/[grnId]/quality">> = Specific
  const handler = {} as typeof import("../../../app/(app)/purchase/grn/[grnId]/quality/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/purchase/grn/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/grn/new">> = Specific
  const handler = {} as typeof import("../../../app/(app)/purchase/grn/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/purchase/grn/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/grn">> = Specific
  const handler = {} as typeof import("../../../app/(app)/purchase/grn/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/purchase/indents/[indentId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/indents/[indentId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/purchase/indents/[indentId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/purchase/indents/approval/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/indents/approval">> = Specific
  const handler = {} as typeof import("../../../app/(app)/purchase/indents/approval/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/purchase/indents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/indents">> = Specific
  const handler = {} as typeof import("../../../app/(app)/purchase/indents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/purchase/lab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/lab">> = Specific
  const handler = {} as typeof import("../../../app/(app)/purchase/lab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/purchase/orders/[poId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/orders/[poId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/purchase/orders/[poId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/purchase/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/orders">> = Specific
  const handler = {} as typeof import("../../../app/(app)/purchase/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/purchase/over-budget/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/over-budget">> = Specific
  const handler = {} as typeof import("../../../app/(app)/purchase/over-budget/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/purchase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase">> = Specific
  const handler = {} as typeof import("../../../app/(app)/purchase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/purchase/po-cancellations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/po-cancellations">> = Specific
  const handler = {} as typeof import("../../../app/(app)/purchase/po-cancellations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/purchase/price-confirmations/[pcId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/price-confirmations/[pcId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/purchase/price-confirmations/[pcId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/purchase/price-confirmations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/price-confirmations">> = Specific
  const handler = {} as typeof import("../../../app/(app)/purchase/price-confirmations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/purchase/procurement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/procurement">> = Specific
  const handler = {} as typeof import("../../../app/(app)/purchase/procurement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/purchase/rate-amendments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/rate-amendments">> = Specific
  const handler = {} as typeof import("../../../app/(app)/purchase/rate-amendments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/purchase/receiving/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/receiving">> = Specific
  const handler = {} as typeof import("../../../app/(app)/purchase/receiving/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/purchase/rfq/[rfqId]/compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/rfq/[rfqId]/compare">> = Specific
  const handler = {} as typeof import("../../../app/(app)/purchase/rfq/[rfqId]/compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/purchase/rfq/[rfqId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/rfq/[rfqId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/purchase/rfq/[rfqId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/purchase/rfq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/rfq">> = Specific
  const handler = {} as typeof import("../../../app/(app)/purchase/rfq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/purchase/vendors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/vendors">> = Specific
  const handler = {} as typeof import("../../../app/(app)/purchase/vendors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/reports/item-ledger/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/item-ledger">> = Specific
  const handler = {} as typeof import("../../../app/(app)/reports/item-ledger/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/reports/item-movement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/item-movement">> = Specific
  const handler = {} as typeof import("../../../app/(app)/reports/item-movement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../../app/(app)/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/reports/purchase-vs-receipt/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/purchase-vs-receipt">> = Specific
  const handler = {} as typeof import("../../../app/(app)/reports/purchase-vs-receipt/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/reports/shipment-pnl/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/shipment-pnl">> = Specific
  const handler = {} as typeof import("../../../app/(app)/reports/shipment-pnl/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/sales/[opportunityId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/[opportunityId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/sales/[opportunityId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/sales/catalogues/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/catalogues">> = Specific
  const handler = {} as typeof import("../../../app/(app)/sales/catalogues/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/sales/cost-sheets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/cost-sheets">> = Specific
  const handler = {} as typeof import("../../../app/(app)/sales/cost-sheets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/sales/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/create">> = Specific
  const handler = {} as typeof import("../../../app/(app)/sales/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/sales/opportunities-costing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/opportunities-costing">> = Specific
  const handler = {} as typeof import("../../../app/(app)/sales/opportunities-costing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/sales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales">> = Specific
  const handler = {} as typeof import("../../../app/(app)/sales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/sales/pipeline-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/pipeline-orders">> = Specific
  const handler = {} as typeof import("../../../app/(app)/sales/pipeline-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/sales/quote-confirmations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/quote-confirmations">> = Specific
  const handler = {} as typeof import("../../../app/(app)/sales/quote-confirmations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/sales/quotes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/quotes">> = Specific
  const handler = {} as typeof import("../../../app/(app)/sales/quotes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/sales/registers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/registers">> = Specific
  const handler = {} as typeof import("../../../app/(app)/sales/registers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/sales/samples-development/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/samples-development">> = Specific
  const handler = {} as typeof import("../../../app/(app)/sales/samples-development/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/sales/samples/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/samples">> = Specific
  const handler = {} as typeof import("../../../app/(app)/sales/samples/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/sales/sq-details/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/sq-details">> = Specific
  const handler = {} as typeof import("../../../app/(app)/sales/sq-details/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/sales/styles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/styles">> = Specific
  const handler = {} as typeof import("../../../app/(app)/sales/styles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/stores/[storeId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stores/[storeId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/stores/[storeId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/stores/adjustments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stores/adjustments">> = Specific
  const handler = {} as typeof import("../../../app/(app)/stores/adjustments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/stores/csp-receipts/[cspId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stores/csp-receipts/[cspId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/stores/csp-receipts/[cspId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/stores/csp-receipts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stores/csp-receipts">> = Specific
  const handler = {} as typeof import("../../../app/(app)/stores/csp-receipts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/stores/interdept/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stores/interdept">> = Specific
  const handler = {} as typeof import("../../../app/(app)/stores/interdept/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/stores/issues/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stores/issues">> = Specific
  const handler = {} as typeof import("../../../app/(app)/stores/issues/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/stores/opening-stock/[openingId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stores/opening-stock/[openingId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/stores/opening-stock/[openingId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/stores/opening-stock/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stores/opening-stock">> = Specific
  const handler = {} as typeof import("../../../app/(app)/stores/opening-stock/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/stores/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stores">> = Specific
  const handler = {} as typeof import("../../../app/(app)/stores/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/stores/process-issues/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stores/process-issues">> = Specific
  const handler = {} as typeof import("../../../app/(app)/stores/process-issues/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/stores/process-orders/[orderId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stores/process-orders/[orderId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/stores/process-orders/[orderId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/stores/process-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stores/process-orders">> = Specific
  const handler = {} as typeof import("../../../app/(app)/stores/process-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/stores/process-receipts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stores/process-receipts">> = Specific
  const handler = {} as typeof import("../../../app/(app)/stores/process-receipts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/stores/processing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stores/processing">> = Specific
  const handler = {} as typeof import("../../../app/(app)/stores/processing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/stores/receipts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stores/receipts">> = Specific
  const handler = {} as typeof import("../../../app/(app)/stores/receipts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/stores/requisitions/[mrsId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stores/requisitions/[mrsId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/stores/requisitions/[mrsId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/stores/requisitions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stores/requisitions">> = Specific
  const handler = {} as typeof import("../../../app/(app)/stores/requisitions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/stores/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stores/setup">> = Specific
  const handler = {} as typeof import("../../../app/(app)/stores/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/stores/transfers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stores/transfers">> = Specific
  const handler = {} as typeof import("../../../app/(app)/stores/transfers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/stores/vendor-returns/[returnId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stores/vendor-returns/[returnId]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/stores/vendor-returns/[returnId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/stores/vendor-returns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stores/vendor-returns">> = Specific
  const handler = {} as typeof import("../../../app/(app)/stores/vendor-returns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/offline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offline">> = Specific
  const handler = {} as typeof import("../../../app/offline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific
  const handler = {} as typeof import("../../../app/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../../app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
