-- ============================================================================
-- Raagam ERP — 0121 Logistics ▸ additional shipment export doc types
-- Commercial lane (band 0100–0199). Widens the shipment_documents.doc_type
-- check to add the remaining export documents (legacy EDP2: Logistics ▸ Shipment
-- ▸ Certificate of Origin / GSP / Single Country Declaration / EP Copy Receipt /
-- BOE / TT Advice). These are optional docs generated by the existing
-- snapshot-based generator; no new table needed. Gated by 'logistics'.
-- ============================================================================

alter table public.shipment_documents
  drop constraint if exists shipment_documents_doc_type_check;

alter table public.shipment_documents
  add constraint shipment_documents_doc_type_check
  check (doc_type in (
    'commercial_invoice','packing_list','bill_of_lading','gst_invoice','dgft',
    'certificate_of_origin','gsp','single_country_declaration',
    'ep_copy_receipt','boe','tt_advice'
  ));
