-- ============================================================================
-- Raagam ERP — 0221 Master Data ▸ Materials ▸ Levies (tax/levy master)
-- Legacy EDP2 "Levy" master: a tax configuration keyed by Type (GST Intra/Inter
-- State) with an effective date and up to four rate components (CGST, SGST,
-- IGST, Cess), each carrying a rate and an Account Head (→ chart of accounts).
-- Too rich for the flat config_lookups engine, so it gets its own table (header
-- only — no child grid). Gated by 'masters' permission (read open, write gated).
-- NOTE: `levy` remains a config_lookups kind from 0219 but is now unused (this
-- table supersedes it) — harmless drift, mirrors how `attribute` was handled.
-- ============================================================================

create table if not exists public.levies (
  id             uuid primary key default gen_random_uuid(),
  entry_no       bigint generated by default as identity,
  levy_date      date not null default current_date,
  type           text not null default 'GST Intra State',
  effective_from date not null default current_date,

  cgst_pct       numeric(6,2) not null default 0,
  cgst_ac_head   uuid references public.gl_accounts(id) on delete set null,
  sgst_pct       numeric(6,2) not null default 0,
  sgst_ac_head   uuid references public.gl_accounts(id) on delete set null,
  igst_pct       numeric(6,2) not null default 0,
  igst_ac_head   uuid references public.gl_accounts(id) on delete set null,

  cess_mode      text not null default 'percent' check (cess_mode in ('percent','amount')),
  cess_value     numeric(12,2) not null default 0,
  cess_ac_head   uuid references public.gl_accounts(id) on delete set null,

  description    text,
  blocked        boolean not null default false,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create trigger trg_levies_updated before update on public.levies
  for each row execute function public.set_updated_at();

-- ---------- RLS (read open like other masters; write gated by 'masters') ----------
do $$
begin
  execute $f$
    create policy levies_read on public.levies for select to authenticated using (true);
    create policy levies_insert on public.levies for insert to authenticated with check (public.has_permission('masters','create'));
    create policy levies_update on public.levies for update to authenticated using (public.has_permission('masters','edit')) with check (public.has_permission('masters','edit'));
    create policy levies_delete on public.levies for delete to authenticated using (public.has_permission('masters','delete'));
  $f$;
  alter table public.levies enable row level security;
end $$;
