-- ============================================================================
-- Raagam ERP — 0229 Master Data ▸ Materials ▸ Out Document Terms (master-detail)
-- Legacy EDP2 "Out Document Term" form: header (Entry No auto · Date · Type
-- [Purchase/Process] · Process → processes · Item Class → item_class master) +
-- a Description line grid (S No · Description free-text). Too rich for the flat
-- config_lookups engine, so it gets its own two tables. RLS = 0218 style.
-- ============================================================================

create table if not exists public.out_document_terms (
  id            uuid primary key default gen_random_uuid(),
  entry_no      bigint generated by default as identity,
  entry_date    date not null default current_date,
  type          text check (type is null or type in ('Purchase','Process')),
  process_id    uuid references public.processes(id),
  item_class_id uuid references public.config_lookups(id),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create trigger trg_out_document_terms_updated before update on public.out_document_terms
  for each row execute function public.set_updated_at();
create index if not exists idx_out_document_terms_process on public.out_document_terms(process_id);
create index if not exists idx_out_document_terms_item_class on public.out_document_terms(item_class_id);

create table if not exists public.out_document_term_lines (
  id                   uuid primary key default gen_random_uuid(),
  out_document_term_id uuid not null references public.out_document_terms(id) on delete cascade,
  sno                  integer not null default 0,
  description          text not null,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);
create trigger trg_out_document_term_lines_updated before update on public.out_document_term_lines
  for each row execute function public.set_updated_at();
create index if not exists idx_out_document_term_lines_parent
  on public.out_document_term_lines(out_document_term_id);

-- ---------- RLS (read open like other masters; write gated by 'masters') ----------
do $$
declare t text;
begin
  foreach t in array array['out_document_terms','out_document_term_lines'] loop
    execute format($f$
      create policy %1$s_read on public.%1$s for select to authenticated using (true);
      create policy %1$s_insert on public.%1$s for insert to authenticated with check (public.has_permission('masters','create'));
      create policy %1$s_update on public.%1$s for update to authenticated using (public.has_permission('masters','edit')) with check (public.has_permission('masters','edit'));
      create policy %1$s_delete on public.%1$s for delete to authenticated using (public.has_permission('masters','delete'));
    $f$, t);
    execute format('alter table public.%I enable row level security;', t);
  end loop;
end $$;
