-- ============================================================================
-- Raagam ERP — 0237 Master Data ▸ Associates ▸ Receivable Terms
-- Legacy EDP2 "Receivable term" form: Entry No (auto) · Date · Pay Mode · an
-- "AT" phrase of 3 dropdowns (basis · when · event) · With Interest · Credit
-- Days · Description · Blocked. Flat header master. RLS = masters.
-- ============================================================================

create table if not exists public.receivable_terms (
  id            uuid primary key default gen_random_uuid(),
  entry_no      bigint generated by default as identity,
  entry_date    date not null default current_date,
  pay_mode      text check (pay_mode is null or pay_mode in (
                  'CHEQUE','DA','DD','DP','LC','OTH','PDC','TT')),
  at_basis      text check (at_basis is null or at_basis in ('SIGHT','OPEN','DAYS')),
  at_when       text check (at_when is null or at_when in ('AFTER','FROM')),
  at_event      text check (at_event is null or at_event in (
                  'SHIPMENT DATE','BL DATE','SIGHT','RECEIPT OF DOCUMENTS',
                  'INVOICE DATE','LC OPEN DATE')),
  with_interest boolean not null default false,
  credit_days   integer not null default 0,
  description   text,
  blocked       boolean not null default false,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create trigger trg_receivable_terms_updated before update on public.receivable_terms
  for each row execute function public.set_updated_at();

-- ---------- RLS (read open like other masters; write gated by 'masters') ----------
do $$
begin
  execute $f$
    create policy receivable_terms_read on public.receivable_terms for select to authenticated using (true);
    create policy receivable_terms_insert on public.receivable_terms for insert to authenticated with check (public.has_permission('masters','create'));
    create policy receivable_terms_update on public.receivable_terms for update to authenticated using (public.has_permission('masters','edit')) with check (public.has_permission('masters','edit'));
    create policy receivable_terms_delete on public.receivable_terms for delete to authenticated using (public.has_permission('masters','delete'));
  $f$;
  alter table public.receivable_terms enable row level security;
end $$;
