-- ============================================================================
-- Raagam ERP — 0254 Master Data ▸ HR ▸ Allowance
-- Legacy EDP2 "Allowance" form (Configure ▸ HR): auto ID · Blocked · Name ·
-- Sequence · Type (Allowance / Other Allowance) · eligibility flags (Base Head ·
-- PF Eligible · ESI Eligible). When Type = "Other Allowance" a second band
-- appears — a Fixed/Variable radio + a (currently unseeded) basis dropdown;
-- both are null/ignored for plain "Allowance". Flat header master. RLS = masters.
-- ============================================================================

create table if not exists public.allowances (
  id            uuid primary key default gen_random_uuid(),
  entry_no      bigint generated by default as identity,   -- the legacy "ID"
  name          text not null,
  sequence      integer not null default 0,
  allowance_type text not null default 'Allowance'
                  check (allowance_type in ('Allowance','Other Allowance')),
  blocked       boolean not null default false,
  base_head     boolean not null default false,
  pf_eligible   boolean not null default false,
  esi_eligible  boolean not null default false,
  -- "Other Allowance" band (null for plain "Allowance")
  calc_type     text check (calc_type is null or calc_type in ('Fixed','Variable')),
  calc_basis    text,                                       -- unseeded legacy dropdown → free text
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create trigger trg_allowances_updated before update on public.allowances
  for each row execute function public.set_updated_at();

-- ---------- RLS (read open like other masters; write gated by 'masters') ----------
do $$
begin
  execute $f$
    create policy allowances_read on public.allowances for select to authenticated using (true);
    create policy allowances_insert on public.allowances for insert to authenticated with check (public.has_permission('masters','create'));
    create policy allowances_update on public.allowances for update to authenticated using (public.has_permission('masters','edit')) with check (public.has_permission('masters','edit'));
    create policy allowances_delete on public.allowances for delete to authenticated using (public.has_permission('masters','delete'));
  $f$;
  alter table public.allowances enable row level security;
end $$;
