-- ============================================================================
-- Raagam ERP — 0255 Master Data ▸ HR ▸ Deduction
-- Legacy EDP2 "Deduction" form (Configure ▸ HR): auto ID · Blocked · Name ·
-- Sequence · Type (Fixed / Variable) · Base Head. A flat header master — the
-- sibling of Allowance (0254) but simpler: its Type radio is the Fixed/Variable
-- calc mode itself (no Allowance/Other wrapper, no PF/ESI eligibility flags).
-- RLS = masters.
-- ============================================================================

create table if not exists public.deductions (
  id          uuid primary key default gen_random_uuid(),
  entry_no    bigint generated by default as identity,   -- the legacy "ID"
  name        text not null,
  sequence    integer not null default 0,
  -- the "Type" radio: Fixed / Variable (null until chosen, matching the blank form)
  calc_type   text check (calc_type is null or calc_type in ('Fixed','Variable')),
  base_head   boolean not null default false,
  blocked     boolean not null default false,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create trigger trg_deductions_updated before update on public.deductions
  for each row execute function public.set_updated_at();

-- ---------- RLS (read open like other masters; write gated by 'masters') ----------
do $$
begin
  execute $f$
    create policy deductions_read on public.deductions for select to authenticated using (true);
    create policy deductions_insert on public.deductions for insert to authenticated with check (public.has_permission('masters','create'));
    create policy deductions_update on public.deductions for update to authenticated using (public.has_permission('masters','edit')) with check (public.has_permission('masters','edit'));
    create policy deductions_delete on public.deductions for delete to authenticated using (public.has_permission('masters','delete'));
  $f$;
  alter table public.deductions enable row level security;
end $$;
