-- ============================================================================
-- Raagam ERP — 0256 Master Data ▸ HR ▸ Holiday
-- Legacy EDP2 "Holiday" form: auto Entry No · Date (entry date) · a Holiday
-- category radio (National / Festival / Others) · Holiday name · a Type radio
-- (Paid Holiday / LOP) · a "Date Range" checkbox with the holiday Date (single
-- date, or a from→to range when Date Range is ticked).
--
-- Flat header master (same shape as receivable_terms / payment_terms). RLS =
-- masters (read open, write gated by has_permission('masters', …)).
-- ============================================================================

create table if not exists public.holidays (
  id            uuid primary key default gen_random_uuid(),
  entry_no      bigint generated by default as identity,
  entry_date    date not null default current_date,
  category      text check (category is null or category in ('National','Festival','Others')),
  name          text not null,
  pay_type      text check (pay_type is null or pay_type in ('Paid Holiday','LOP')),
  is_date_range boolean not null default false,
  holiday_date  date not null,               -- the holiday (or range start)
  end_date      date,                         -- range end (when is_date_range)
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create trigger trg_holidays_updated before update on public.holidays
  for each row execute function public.set_updated_at();
create index if not exists idx_holidays_date on public.holidays(holiday_date);

-- ---------- RLS (read open like other masters; write gated by 'masters') ----------
do $$
begin
  execute $f$
    create policy holidays_read on public.holidays for select to authenticated using (true);
    create policy holidays_insert on public.holidays for insert to authenticated with check (public.has_permission('masters','create'));
    create policy holidays_update on public.holidays for update to authenticated using (public.has_permission('masters','edit')) with check (public.has_permission('masters','edit'));
    create policy holidays_delete on public.holidays for delete to authenticated using (public.has_permission('masters','delete'));
  $f$;
  alter table public.holidays enable row level security;
end $$;
