-- ============================================================================
-- Raagam ERP — 0256 Master Data ▸ HR ▸ Work Timing (master-detail)
-- Legacy EDP2 "Work Timing" form (screenshot _145932): header (Entry No auto ·
-- Date · Location red ⓘ → locations · Effective From) + a Shift line grid
-- (S No · Shift Category ⓘ · No Of Shifts · Applicable For All Categories) +
-- Save / Save As Drafts (→ is_draft).
-- Location reuses the `locations` GST-entity master; Shift Category = new
-- config_lookups kind 'shift_category' (Add/Modify via LookupDialogPicker).
-- RLS = masters (read open, write gated by has_permission('masters', …)).
-- ============================================================================

-- 1) Widen the config_lookups kind CHECK (re-add every kind — 0247 shape — +1).
alter table public.config_lookups drop constraint if exists config_lookups_kind_check;
alter table public.config_lookups add constraint config_lookups_kind_check
  check (kind in (
    'attribute','levy','material_category','material_attribute','yarn_count',
    'yarn_purity','composition','process','component','gauge','knitting_dia',
    'out_doc_term','commodity','item_class','hsn_code','city','state','department',
    'designation','internal_department','ship_type','payment_term','employee_category',
    'team','account_schedule','vendor_group','agent_type','agent','packing_list_format',
    'commercial_invoice_format','shift_category'
  ));

-- 2) Work Timing header.
create table if not exists public.work_timings (
  id             uuid primary key default gen_random_uuid(),
  entry_no       bigint generated by default as identity,
  date           date not null default current_date,
  location_id    uuid references public.locations(id) on delete set null,
  effective_from date not null default current_date,
  is_draft       boolean not null default false,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create trigger trg_work_timings_updated before update on public.work_timings
  for each row execute function public.set_updated_at();
create index if not exists idx_work_timings_location on public.work_timings(location_id);

-- 3) Shift line grid.
create table if not exists public.work_timing_lines (
  id                            uuid primary key default gen_random_uuid(),
  work_timing_id                uuid not null references public.work_timings(id) on delete cascade,
  sno                           integer not null default 0,
  shift_category_id             uuid references public.config_lookups(id) on delete set null,
  no_of_shifts                  integer,
  applicable_for_all_categories boolean not null default false,
  created_at                    timestamptz not null default now(),
  updated_at                    timestamptz not null default now()
);
create trigger trg_work_timing_lines_updated before update on public.work_timing_lines
  for each row execute function public.set_updated_at();
create index if not exists idx_work_timing_lines_parent on public.work_timing_lines(work_timing_id);

-- 4) RLS (read open like other masters; write gated by 'masters').
do $$
declare t text;
begin
  foreach t in array array['work_timings','work_timing_lines'] loop
    execute format($f$
      create policy %1$s_read on public.%1$s for select to authenticated using (true);
      create policy %1$s_insert on public.%1$s for insert to authenticated with check (public.has_permission('masters','create'));
      create policy %1$s_update on public.%1$s for update to authenticated using (public.has_permission('masters','edit')) with check (public.has_permission('masters','edit'));
      create policy %1$s_delete on public.%1$s for delete to authenticated using (public.has_permission('masters','delete'));
    $f$, t);
    execute format('alter table public.%I enable row level security;', t);
  end loop;
end $$;
