-- ============================================================================
-- Raagam ERP — 0258 Master Data ▸ HR ▸ Working Hour (flat master)
-- Legacy EDP2 "Working Hour" form (screenshot _152733): Entry No auto · Date +
-- a set of daily time slots — Morning In · Morning Break From/To · Lunch Break
-- From/To · Evening Break From/To · Evening Out · OT In · OT Out — all `time`
-- values. Save / Save As Drafts (→ is_draft). No picker fields.
-- RLS = masters (read open, write gated by has_permission('masters', …)).
-- ============================================================================

create table if not exists public.working_hours (
  id                 uuid primary key default gen_random_uuid(),
  entry_no           bigint generated by default as identity,
  date               date not null default current_date,
  morning_in         time,
  morning_break_from time,
  morning_break_to   time,
  lunch_break_from   time,
  lunch_break_to     time,
  evening_break_from time,
  evening_break_to   time,
  evening_out        time,
  ot_in              time,
  ot_out             time,
  is_draft           boolean not null default false,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
create trigger trg_working_hours_updated before update on public.working_hours
  for each row execute function public.set_updated_at();

do $$
begin
  execute $f$
    create policy working_hours_read on public.working_hours for select to authenticated using (true);
    create policy working_hours_insert on public.working_hours for insert to authenticated with check (public.has_permission('masters','create'));
    create policy working_hours_update on public.working_hours for update to authenticated using (public.has_permission('masters','edit')) with check (public.has_permission('masters','edit'));
    create policy working_hours_delete on public.working_hours for delete to authenticated using (public.has_permission('masters','delete'));
  $f$;
  alter table public.working_hours enable row level security;
end $$;
