-- ============================================================================
-- Raagam ERP — 0261 Master Data ▸ HR ▸ PF ESI Control
-- Legacy EDP2 "PF ESI Control" form: a dated rate-version master —
--   Entry No (auto) · Date · Effective From Date ·
--   Employee Contribution (PF % · ESI %) · Employer Contribution (PF % · ESI %)
-- Entries accumulate over time (each a rate revision effective from a date).
-- Flat master, no children. RLS = masters.
-- ============================================================================

create table if not exists public.pf_esi_controls (
  id             uuid primary key default gen_random_uuid(),
  entry_no       bigint generated by default as identity,
  entry_date     date not null default current_date,
  effective_from date not null default current_date,
  emp_pf_pct     numeric(6,2) not null default 0,   -- Employee contribution
  emp_esi_pct    numeric(6,2) not null default 0,
  empr_pf_pct    numeric(6,2) not null default 0,   -- Employer contribution
  empr_esi_pct   numeric(6,2) not null default 0,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create trigger trg_pf_esi_controls_updated before update on public.pf_esi_controls
  for each row execute function public.set_updated_at();

-- ---------- RLS (read open like other masters; write gated by 'masters') ----------
do $$
begin
  execute $f$
    create policy pf_esi_controls_read on public.pf_esi_controls for select to authenticated using (true);
    create policy pf_esi_controls_insert on public.pf_esi_controls for insert to authenticated with check (public.has_permission('masters','create'));
    create policy pf_esi_controls_update on public.pf_esi_controls for update to authenticated using (public.has_permission('masters','edit')) with check (public.has_permission('masters','edit'));
    create policy pf_esi_controls_delete on public.pf_esi_controls for delete to authenticated using (public.has_permission('masters','delete'));
  $f$;
  alter table public.pf_esi_controls enable row level security;
end $$;
