-- ============================================================================
-- Raagam ERP — 0264 Master Data ▸ System ▸ Garment Rejection Rule
-- Legacy EDP2 "Garment rejection rule" form: header (auto Entry No · Effective
-- From · Rule [name] · Blocked) + a "Details" child grid of tiers
-- (S No · Range · From · To · Rejection Allowance).
--
-- Master-detail (same shape as Bank/Consignee). RLS = masters (read open, write
-- gated by has_permission('masters', …)). `range` → column `range_label` to
-- avoid the Postgres RANGE type keyword.
-- ============================================================================

create table if not exists public.garment_rejection_rules (
  id             uuid primary key default gen_random_uuid(),
  entry_no       bigint generated by default as identity,
  effective_from date not null default current_date,
  rule           text,
  blocked        boolean not null default false,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create trigger trg_garment_rejection_rules_updated before update on public.garment_rejection_rules
  for each row execute function public.set_updated_at();

create table if not exists public.garment_rejection_rule_lines (
  id                  uuid primary key default gen_random_uuid(),
  rule_id             uuid not null references public.garment_rejection_rules(id) on delete cascade,
  sno                 integer not null default 0,
  range_label         text,            -- "Range"
  from_value          numeric,         -- "From"
  to_value            numeric,         -- "To"
  rejection_allowance numeric,         -- "Rejection Allowance"
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);
create trigger trg_garment_rejection_rule_lines_updated before update on public.garment_rejection_rule_lines
  for each row execute function public.set_updated_at();
create index if not exists idx_grr_lines_rule on public.garment_rejection_rule_lines(rule_id);

-- ---------- RLS (read open like other masters; write gated by 'masters') ----------
do $$
declare t text;
begin
  foreach t in array array['garment_rejection_rules','garment_rejection_rule_lines'] loop
    execute format($f$
      create policy %1$s_read on public.%1$s for select to authenticated using (true);
      create policy %1$s_insert on public.%1$s for insert to authenticated with check (public.has_permission('masters','create'));
      create policy %1$s_update on public.%1$s for update to authenticated using (public.has_permission('masters','edit')) with check (public.has_permission('masters','edit'));
      create policy %1$s_delete on public.%1$s for delete to authenticated using (public.has_permission('masters','delete'));
    $f$, t);
    execute format('alter table public.%I enable row level security;', t);
  end loop;
end $$;
