-- ============================================================================
-- Raagam ERP — 0264 Master Data ▸ System ▸ Document No format
-- Legacy EDP2 "Document No format" form (screenshot _175243): a THREE-level
-- nested master-detail —
--   Header : Entry No auto · Date · Track (red ⓘ → config_lookups 'doc_track')
--   Grid 1 : "Menu" rows — Menu (ⓘ 'doc_menu') · Location wise · Starting SlNo ·
--            Sample DocNo
--   Grid 2 : per-menu "segment" lines that compose the document number —
--            Value Type (ⓘ 'doc_value_type') · Value · Seperator · No Of Digits ·
--            Value From (▼ 'doc_value_from') · Ref. only
-- + Save / Save As Drafts (→ is_draft). All list fields Add/Modify via the
-- shared LookupDialogPicker (config_lookups kinds).
-- RLS = masters (read open, write gated by has_permission('masters', …)).
-- ============================================================================

-- 1) Widen the config_lookups kind CHECK (re-add every live kind + 4 new).
alter table public.config_lookups drop constraint if exists config_lookups_kind_check;
alter table public.config_lookups add constraint config_lookups_kind_check
  check (kind in (
    'attribute','levy','material_category','material_attribute','yarn_count',
    'yarn_purity','composition','process','component','gauge','knitting_dia',
    'out_doc_term','commodity','item_class','hsn_code','city','state','department',
    'designation','internal_department','ship_type','payment_term','employee_category',
    'team','account_schedule','vendor_group','agent_type','agent','packing_list_format',
    'commercial_invoice_format','shift_category',
    'doc_track','doc_menu','doc_value_type','doc_value_from'
  ));

-- 2) Header.
create table if not exists public.document_no_formats (
  id         uuid primary key default gen_random_uuid(),
  entry_no   bigint generated by default as identity,
  date       date not null default current_date,
  track_id   uuid references public.config_lookups(id) on delete set null,
  is_draft   boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger trg_document_no_formats_updated before update on public.document_no_formats
  for each row execute function public.set_updated_at();

-- 3) Grid 1 — Menu rows.
create table if not exists public.document_no_format_menus (
  id             uuid primary key default gen_random_uuid(),
  format_id      uuid not null references public.document_no_formats(id) on delete cascade,
  sno            integer not null default 0,
  menu_id        uuid references public.config_lookups(id) on delete set null,
  location_wise  boolean not null default false,
  starting_sl_no integer not null default 0,
  sample_doc_no  text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create trigger trg_document_no_format_menus_updated before update on public.document_no_format_menus
  for each row execute function public.set_updated_at();
create index if not exists idx_docno_menus_format on public.document_no_format_menus(format_id);

-- 4) Grid 2 — per-menu segment lines.
create table if not exists public.document_no_format_segments (
  id             uuid primary key default gen_random_uuid(),
  format_menu_id uuid not null references public.document_no_format_menus(id) on delete cascade,
  sno            integer not null default 0,
  value_type_id  uuid references public.config_lookups(id) on delete set null,
  value          text,
  separator      text,
  no_of_digits   integer,
  value_from_id  uuid references public.config_lookups(id) on delete set null,
  ref_only       boolean not null default false,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create trigger trg_document_no_format_segments_updated before update on public.document_no_format_segments
  for each row execute function public.set_updated_at();
create index if not exists idx_docno_segments_menu on public.document_no_format_segments(format_menu_id);

-- 5) RLS.
do $$
declare t text;
begin
  foreach t in array array[
    'document_no_formats','document_no_format_menus','document_no_format_segments'
  ] loop
    execute format($f$
      create policy %1$s_read on public.%1$s for select to authenticated using (true);
      create policy %1$s_insert on public.%1$s for insert to authenticated with check (public.has_permission('masters','create'));
      create policy %1$s_update on public.%1$s for update to authenticated using (public.has_permission('masters','edit')) with check (public.has_permission('masters','edit'));
      create policy %1$s_delete on public.%1$s for delete to authenticated using (public.has_permission('masters','delete'));
    $f$, t);
    execute format('alter table public.%I enable row level security;', t);
  end loop;
end $$;
