-- ============================================================================
-- Raagam ERP — 0294 Master Data ▸ Materials ▸ Processes import (legacy)
-- Seeds the legacy 'Processes - U2' report (438 rows). Commodity ShortName
-- is blank for every row in the source report (processes.commodity_id stays
-- NULL for this import — see 0293 for the FK repoint that benefits future
-- rows). HSN Code is free text, populated only where the report has a
-- value (7 rows). Created Dt/User are populated where present (219 rows);
-- the remaining rows default created_at to now() via coalesce and leave
-- created_by NULL, mirroring how config_lookups' legacy import (0290-style)
-- handles missing per-row provenance. sl_no is imported verbatim, no
-- interpretation attempted (see 0293's header comment).
-- ============================================================================

insert into public.processes (
  name, hsn_code, for_yarn, for_fabric, for_trims, for_garments, for_components,
  has_sub_categories, designwise_delivery, sl_no, created_at, created_by, blocked
)
select
  v.name, v.hsn_code, v.for_yarn, v.for_fabric, v.for_trims, v.for_garments, v.for_components,
  v.has_sub_categories, v.designwise_delivery, v.sl_no,
  coalesce(v.created_dt::timestamptz, now()), v.created_by, v.blocked
from (values
  ('ACID WASHING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('ALL OVER EMBROIDERY', NULL, false, true, false, false, false, false, false, 9, '2024-04-24', 'admin', false),
  ('AOP BIT PRINTING', NULL, false, false, false, false, true, false, false, 9, '2020-07-28', 'admin', false),
  ('AOP BIT PRINTING [BACK]', NULL, false, false, false, false, true, false, false, 9, '2021-12-29', 'ADMIN', false),
  ('AOP BIT PRINTING [FRONT]', NULL, false, false, false, false, true, false, false, 9, '2021-12-29', 'ADMIN', false),
  ('AOP BIT PRINTING [SLEEVE]', NULL, false, false, false, false, true, false, false, 9, '2021-12-29', 'ADMIN', false),
  ('APPLIQUE CUTTING', NULL, false, false, false, false, true, false, false, 9, '2014-01-20', 'admin', false),
  ('APPLIQUE EMBROIDERY', '2041', false, false, false, false, true, false, false, 9, '2016-03-18', 'PRABHU', false),
  ('APPLIQUE PRINTING', NULL, false, false, false, false, true, false, false, 9, '2016-03-19', 'SAKTHIVEL', false),
  ('APPLIQUE PROCESS', NULL, false, false, false, true, false, false, false, 9, '2019-08-26', 'admin', false),
  ('ARMHOLE JOINT', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('ASSORT PACKING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('ATTACH MOBILAN TAPE', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BACK SPIKE ATTACH', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BAG/CHECKING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BAG/IRONING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BAG/PACKING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BAG/POWERTABLE', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BAG/RE-IRONING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BAG/SINGER', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BARTACK', '2094', false, false, false, true, false, true, true, 9, '2019-08-21', 'sowmiyaraj', false),
  ('BARTACK & BUTTON', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BARTACK ONLY', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BARTACK/2', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BARTACKING', NULL, false, false, false, false, true, false, false, 99, '2017-02-03', 'm.prabhu', false),
  ('BATCH ATTACH', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BATCH ATTACHING', NULL, false, false, false, false, true, false, false, 99, '2017-08-13', 'raju', false),
  ('BELT FIVE THREAD', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BELT FLATLOCK', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BELT READY & ATTACH', NULL, false, false, false, true, false, false, false, 9, '2021-06-15', 'admin', false),
  ('BIO WASH AFTER COMPACTING', NULL, false, true, false, false, false, false, false, 9, '2023-08-18', 'ADMIN', false),
  ('BIT FORM CUTTING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BIT PRINTING', NULL, false, false, false, false, true, false, false, 99, '2017-03-10', 'admin', false),
  ('BIT PRINTING[BACK]', NULL, false, false, false, true, true, false, false, 9, '2022-02-09', 'admin', false),
  ('BIT PRINTING[FRONT]', NULL, false, false, false, true, true, false, false, 9, '2022-02-09', 'admin', false),
  ('BIT PRINTING[LEFT SLEEVE]', NULL, false, false, false, true, true, false, false, 9, '2022-04-22', 'admin', false),
  ('BIT PRINTING[RIGHT SLEEVE]', NULL, false, false, false, true, true, false, false, 9, '2022-04-22', 'admin', false),
  ('BIT PRINTING[SLEEVE]', NULL, false, false, false, true, true, false, false, 9, '2022-02-12', 'admin', false),
  ('BIT WASHING', NULL, false, false, false, false, true, false, false, 9, '2014-01-20', 'admin', false),
  ('BITWASH[TEST]', NULL, false, true, false, false, false, false, false, 9, '2025-06-25', 'admin', false),
  ('BLEACHING', NULL, false, true, false, false, false, false, false, 9, '2014-01-20', 'admin', false),
  ('BLEASHING', NULL, false, true, false, false, false, false, false, 9, '2016-04-20', 'SIVAKUMAR', true),
  ('BODY DOWER', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BODY ELASTIC CUT', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BODY HEM', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BOTTOM GATHERING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BOTTOM PEEK', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BOTTOM RIB READY', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BOTTOM STITCH &MOBIL', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BOW ATTACH', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BOW ATTACHING', NULL, false, false, false, true, true, false, false, 9, '2014-01-20', 'admin', false),
  ('BOW MAKING', NULL, false, false, true, false, false, false, false, 9, '2014-01-20', 'admin', false),
  ('BOW TURNING', NULL, false, false, false, true, true, false, false, 9, '2021-04-13', 'admin', false),
  ('BOW[CUTTING&TURNING]', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BOW[CUTTING]', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BRAIDING', NULL, false, false, false, false, true, false, false, 9, '2014-01-20', 'admin', false),
  ('BRIDAL WORK', NULL, false, true, false, false, false, false, false, 9, '2018-09-29', 'm.prabhu', false),
  ('BRILL SIDE JOINT', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BRILL&BODY ATTACH', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BRUSHING', NULL, false, true, false, false, false, false, false, 9, '2014-01-20', 'admin', false),
  ('BUFF PRINTING', NULL, false, false, false, false, true, false, false, 99, '2017-08-13', 'raju', false),
  ('BUNDLING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BURN OUT', NULL, false, true, false, false, false, false, false, 9, '2016-10-05', 'sivakumar', false),
  ('BURN OUT WASH', NULL, false, false, false, true, false, false, false, 9, '2019-02-16', 'Balaji', false),
  ('BURNOT', NULL, false, true, false, false, false, false, false, 9, '2016-10-05', 'sivakumar', false),
  ('BURNOUT WASHING', NULL, false, false, false, true, true, false, false, 9, '2020-08-11', 'admin', false),
  ('BUTTON ATTACHING', NULL, false, false, false, true, false, false, false, 99, '2017-07-21', 'SANTHANA', false),
  ('BUTTON HAND WORK', NULL, false, false, false, true, false, false, false, 9, '2016-11-30', 'RAJU', false),
  ('BUTTON ONLY', NULL, false, false, false, false, false, false, false, 99, NULL, NULL, false),
  ('BUTTON(4NOS)', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BUTTON(5NOS)', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BUTTON(6NOS)', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('BUTTONING', NULL, false, false, false, false, true, false, false, 9, '2016-03-19', 'SAKTHIVEL', false),
  ('CALENDERING', NULL, false, false, true, false, false, false, false, 9, '2022-09-06', 'admin', false),
  ('CAPE ATTACH', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('CAPE INNER PEEK', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('CAPE LOOP READY', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('CAPE OUTLINE', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('CAPE PEEK', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('CAPE TACK WITH BODY', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('CARTON PACKING ONLY', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('CERTIN TAPE', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('CHECKING', NULL, false, false, false, true, false, false, false, 9, '2014-01-20', 'admin', false),
  ('CHECKING/RATE REVISE', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('CHECKING[BEFORE DYEI', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('CHENNILLE EMB', NULL, false, false, false, false, true, false, false, 9, '2020-06-22', 'Selvan', false),
  ('CHEST PRINT AT FRONT', NULL, false, false, false, true, false, false, false, 9, '2019-02-16', 'Balaji', false),
  ('CHEST PRINTING', NULL, false, true, false, false, false, false, false, 9, '2019-04-08', 'MOHAN', false),
  ('CMYK PRINT', NULL, false, false, false, true, true, false, false, 9, '2016-03-12', 'admin', false),
  ('COLLAR ATTACH', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('COLLAR CLOSING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('COLLAR READY', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('COLLAR SEPARATION', NULL, false, true, false, false, false, false, false, 9, '2014-01-20', 'admin', false),
  ('COLLER, PEEK READY', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('COMPACTING', NULL, false, true, false, false, false, true, false, 9, '2014-01-20', 'admin', false),
  ('COMPONENT PRINT', NULL, false, false, false, false, true, false, false, 9, '2016-06-11', 'M.Prabhu', false),
  ('COMPONENTS FROM BIT FORM', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('COMPONENTS FROM FABRIC - PANEL FORM', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('CONE WINDING', NULL, true, false, false, false, false, false, false, 9, '2016-03-05', 'admin', false),
  ('CONTAMINATION REMOVAL', NULL, false, false, false, true, true, false, false, 9, '2014-01-20', 'admin', false),
  ('CONVERSION', NULL, true, false, false, false, false, false, false, 9, '2014-01-20', 'admin', false),
  ('COTTON BOX& RE PACK', NULL, false, false, false, false, true, false, false, 9, '2020-08-13', 'production', false),
  ('COUNTING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('CPD WASHING', NULL, false, false, false, true, true, false, false, 9, '2024-01-08', 'admin', false),
  ('CPL WASHING', NULL, false, false, false, false, true, false, false, 9, '2019-07-12', 'ranjith', false),
  ('CROPPING', NULL, false, true, false, false, false, false, false, 9, '2024-07-18', 'admin', false),
  ('CUFF SEPARATION', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('CURING', NULL, false, false, false, true, true, false, false, 9, '2016-07-20', 'admin', false),
  ('CUT PANEL CHECKING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('CUT PANEL CHECKING/2', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('CUT PANEL SETTING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('CUTTING', NULL, false, false, false, true, false, false, false, 9, '2014-01-20', 'admin', false),
  ('CUTTING RATE REVISED', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('CUTTING[PATTI,CLR,CF', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('DIGITAL PRINTING', NULL, false, false, false, false, true, false, false, 9, '2019-09-05', 'Nandhakumar', false),
  ('DIP DYEING', NULL, false, false, false, true, true, false, false, 9, '2014-01-20', 'admin', false),
  ('DIP STENTERING', NULL, false, true, false, false, false, false, false, 9, '2023-10-11', 'admin', false),
  ('DIP WASHING', NULL, false, true, false, false, false, false, false, 9, '2016-03-21', 'SIVAKUMAR', false),
  ('DISCHARGE PRINTING', NULL, false, false, false, true, true, false, false, 9, '2014-01-20', 'admin', false),
  ('DRIER', NULL, false, false, false, true, true, false, false, 9, '2021-12-10', 'ADMIN', false),
  ('DRIMMER', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('DUST REMOVAL', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('DYEING', NULL, false, true, false, false, false, true, false, 6, '2014-01-20', 'admin', false),
  ('DYEING AFTER AOP', NULL, false, true, false, false, false, false, false, 9, '2016-10-07', 'Admin', false),
  ('ELASTIC ATTACH', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('ELASTIC ATTACHING', NULL, false, false, false, true, true, false, false, 9, '2014-01-20', 'admin', false),
  ('ELASTIC BOTTOM CLOSE', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('ELASTIC COVERING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('ELASTIC EDGE STITCH', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('ELASTOMERIC WASH', NULL, false, true, false, false, false, false, false, 9, '2022-12-06', 'admin', false),
  ('EMBOSS PRINTING', NULL, false, false, false, true, false, false, false, 99, '2018-03-23', 'SANTHANA', false),
  ('EMBOSS PRINTING', NULL, false, false, false, true, false, false, false, 9, '2024-08-02', 'brindha', false),
  ('EMBOSSING', NULL, false, false, false, true, false, false, false, 9, '2024-09-02', 'admin', false),
  ('EMBR0IDERY', NULL, false, false, false, true, true, false, false, 9, '2022-07-05', 'ADMIN', false),
  ('EMBROIDER AND HAND EMBROIDRY', NULL, false, false, false, false, true, false, false, 99, '2017-06-20', 'SANTHANA', false),
  ('EMBROIDERY', '2003', false, false, false, true, true, true, false, 9, '2018-07-31', 'SAKTHI', false),
  ('EMBROIDERY [BACK]', NULL, false, false, false, true, true, false, false, 9, '2024-04-13', 'ADMIN', false),
  ('EMBROIDERY [FRONT]', NULL, false, false, false, true, true, false, false, 9, '2024-04-13', 'ADMIN', false),
  ('EMBROIDERY [LEFT SLV]', NULL, false, false, false, false, true, false, false, 9, '2026-07-08', 'ADMIN', false),
  ('EMBROIDERY [RIGHT SLV]', NULL, false, false, false, false, true, false, false, 9, '2026-07-08', 'ADMIN', false),
  ('EMBROIDERY [SLEEVE]', NULL, false, false, false, true, true, false, false, 9, '2025-04-07', 'admin', false),
  ('EMMING', NULL, false, false, false, false, false, false, false, 99, NULL, NULL, false),
  ('EYELET ATTACHING', NULL, false, false, true, false, false, false, false, 99, '2017-06-24', 'SANTHANA', false),
  ('EYELET ATTACHMENT', NULL, false, false, false, false, true, false, false, 99, '2017-07-01', 'santhana', false),
  ('EYELET ATTAMENT', NULL, false, false, true, false, false, false, false, 99, '2017-06-24', 'SANTHANA', false),
  ('EYELET FIXING', NULL, false, false, true, false, false, false, false, 9, '2014-01-20', 'admin', false),
  ('EYELET ONLY', NULL, false, false, false, false, false, false, false, 99, NULL, NULL, false),
  ('FABRIC PURCHASE', NULL, false, true, false, false, false, false, false, 2, '2014-01-20', 'admin', false),
  ('FINAL CHECKING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('FINISHING', NULL, false, false, false, true, false, false, false, 9, '2014-01-20', 'admin', false),
  ('FLAG LABLE', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('FLOCK PRINTING', NULL, false, false, false, false, true, false, true, 9, '2016-03-19', 'raju', false),
  ('FOAM CUTTING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('FOAM FUSING', NULL, false, false, false, true, true, false, false, 9, '2016-04-04', 'Raju', false),
  ('FOAM FUSING[BIG]', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('FOAM FUSING[FRONT]', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('FOAM FUSING[II ND]', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('FOAM FUSING[PATTI]', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('FOAM FUSING[POCKET]', NULL, false, false, false, true, true, false, false, 9, '2022-02-08', 'ADMIN', false),
  ('FOIL PRINTING', NULL, false, false, false, false, true, false, false, 9, '2016-05-03', 'RAJU', false),
  ('FRONT SPIKE ATTACH', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('FULL OPEN PATTI', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('FUSING', NULL, false, false, false, true, true, false, false, 9, '2014-01-20', 'admin', false),
  ('FUSING(TRIMS)', NULL, false, false, true, false, false, false, false, 9, '2025-06-16', 'admin', false),
  ('GADA PRINTING', NULL, false, false, false, false, true, false, false, 9, '2016-07-15', 'm.prabhu', false),
  ('GARMENT DYEING', NULL, false, false, false, true, true, false, false, 9, '2014-01-20', 'admin', false),
  ('GARMENT DYEING[LAVA DYEING]', NULL, false, false, false, true, true, false, false, 9, '2025-05-12', 'admin', false),
  ('GARMENT EMBROIDERY', NULL, false, false, false, true, true, false, false, 9, '2014-01-20', 'admin', false),
  ('GARMENT PRINTING', NULL, false, false, false, true, true, false, false, 9, '2014-01-20', 'admin', false),
  ('GARMENT PURCHASE', NULL, false, false, false, true, false, false, false, 9, '2014-01-20', 'admin', false),
  ('GARMENT TIE & DYE', NULL, false, false, false, true, true, false, false, 9, '2014-01-20', 'admin', false),
  ('GARMENT TIP DYE', NULL, false, false, false, true, false, false, false, 9, '2024-09-03', 'admin', false),
  ('GARMENT WASHING', NULL, false, false, false, true, true, true, false, 9, '2014-01-20', 'admin', false),
  ('GLITTER PRINTING', NULL, false, false, false, false, true, false, false, 9, '2016-03-18', 'PRABHU', false),
  ('GREY TO FINISH REACTIVE AOP', NULL, false, true, false, false, false, false, false, 9, '2025-02-10', 'admin', false),
  ('GRINDING', NULL, false, false, false, true, true, false, false, 9, '2024-01-05', 'admin', false),
  ('HAND EMBROIDERY', NULL, false, false, false, false, true, false, false, 9, '2016-11-30', 'RAJU', false),
  ('HAND PRINT', NULL, false, false, false, true, false, false, false, 9, '2018-09-29', 'SAKTHI', false),
  ('HAND SEQUENCE EMB', NULL, false, false, false, false, false, false, false, 99, NULL, NULL, false),
  ('HAND WORK', NULL, false, false, false, true, true, false, false, 9, '2016-04-15', 'Raju', false),
  ('HD PRINT', '2025', false, false, false, false, true, false, false, 99, '2017-01-19', 'RAJU', false),
  ('HEART CUT & EMB SEQ', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('HEAT SETTING', NULL, false, true, false, false, false, false, false, 9, '2014-01-20', 'admin', false),
  ('HEMMING STITCH', NULL, false, false, false, false, false, false, false, 99, NULL, NULL, false),
  ('HOOD & BODY FULL ATT', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('HOOD INNER PEEK', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('HOT WASHING', NULL, false, true, false, false, false, false, false, 9, '2019-03-26', 'jaganathan', false),
  ('HYDRO/NATURAL DRYER', NULL, false, true, false, false, false, false, false, 9, '2025-09-13', 'admin', false),
  ('HYDRO/NATURNAL DRYER', NULL, false, false, true, false, false, false, false, 9, '2026-06-13', 'Ilamathi', false),
  ('IIIUH', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('INNER ATTACH', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('INSPECTION RECLOSE', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('IRONING', NULL, false, false, false, true, false, false, false, 9, '2014-01-20', 'admin', false),
  ('IRONING [4 FOLD]', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('IRONING RATE REVISED', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('IRONING(FOAM)', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('IRONING,', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('IRONING/INSPECTED PC', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('IRONING/PLACKET', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('KAJA', NULL, false, false, false, true, true, false, false, 9, '2014-01-20', 'admin', false),
  ('KAJA & BARTACK', NULL, false, false, false, false, false, false, false, 99, NULL, NULL, false),
  ('KAJA & BUTTON', NULL, false, false, false, true, true, false, false, 9, '2014-01-20', 'admin', false),
  ('KAJA & BUTTON(5X5)', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('KAJA & BUTTON(6X6)', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('KAJA BUTTON', NULL, false, false, false, false, false, false, false, 99, NULL, NULL, false),
  ('KAJA ONLY', NULL, false, false, false, false, false, false, false, 99, NULL, NULL, false),
  ('KAJA WITH FOAM', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('KAJA WITH FOAM&BARTA', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('KAJA,BUTTON & BARTAC', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('KANGAROO POCKET', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('KNITTING', NULL, false, true, false, false, false, false, false, 5, '2014-01-20', 'admin', false),
  ('LABEL ATTACH', NULL, false, false, false, true, true, false, false, 9, '2016-12-26', 'admin', false),
  ('LABEL[AFTER DYEING]', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('LABLE READY', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('LACE & ZIP ATTACH', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('LASER CUTTING', NULL, false, true, false, false, false, false, false, 9, '2020-10-27', 'admin', false),
  ('LASER CUTTING/TRIMS', NULL, false, false, true, false, false, false, false, 9, '2023-10-10', 'admin', false),
  ('LEG DOWER', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('LEG HEM', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('LINE SETTING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('LUBRICANT WASH', NULL, false, false, false, true, true, false, false, 9, '2025-03-12', 'admin', false),
  ('MAIN LABLE', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('MATTE FUSING', NULL, false, false, false, true, true, false, false, 9, '2022-03-16', 'admin', false),
  ('MENDING', NULL, false, false, false, true, true, false, false, 9, '2014-01-20', 'admin', false),
  ('MENNDING', NULL, false, false, false, false, false, false, false, 99, NULL, NULL, true),
  ('MERCERISING', NULL, false, true, false, false, false, false, false, 9, '2022-08-23', 'admin', false),
  ('MESH ATTACH', NULL, false, false, false, false, false, false, false, 99, NULL, NULL, false),
  ('MESH CUTTING', NULL, false, false, false, true, true, false, false, 9, '2021-04-26', 'admin', false),
  ('METAL BATCH', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('MOBILE POCKET', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('MOULDING', NULL, false, false, true, false, false, false, false, 9, '2014-01-20', 'admin', false),
  ('MULTIPLE PROCESS', NULL, false, true, false, false, false, false, false, 9, '2015-03-12', 'admin', false),
  ('NECK FOLDING', NULL, false, false, false, true, true, false, false, 9, '2022-02-02', 'admin', false),
  ('NECK LABLE', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('NECK RIB ATTACH', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('NECK TAPE PRINTING', NULL, false, false, false, false, true, false, false, 9, '2016-07-14', 'm.prabhu', false),
  ('NET FOLDING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('NON PVC PRINTING', NULL, false, false, false, false, true, false, false, 99, '2017-04-08', 'Balaji', false),
  ('OIL REMOVING', NULL, false, false, false, false, false, false, false, 99, NULL, NULL, false),
  ('OIL STAIN', NULL, false, false, false, false, false, false, false, 99, NULL, NULL, true),
  ('OS EMBROIDERY', NULL, false, false, false, true, false, false, false, 9, '2019-09-18', 'admin', false),
  ('OTHERS', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('OVER DYEING', NULL, false, true, false, false, false, false, false, 9, '2019-11-15', 'admin', false),
  ('PACK FOLDING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('PACK/TISSUE PAPER', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('PACKING', NULL, false, false, false, true, false, false, false, 9, '2014-01-20', 'admin', false),
  ('PACKING RATE REVISED', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('PACKING(3 PCS PK)', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('PACKING(5PCS PK)', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('PACKING,', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('PACKING/INSPECTED PC', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('PAINTING', NULL, false, false, true, false, false, false, false, 9, '2014-01-20', 'admin', false),
  ('PALCKET CLOSING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('PALCKET READY', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('PANEL WASHING', NULL, false, false, false, false, true, false, false, 9, '2014-01-20', 'admin', false),
  ('PANT ELASTIC', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('PATTI', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('PEACHING', NULL, false, true, false, false, false, false, false, 9, '2014-01-20', 'admin', false),
  ('PEEK', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('PICOTING', NULL, false, false, false, true, true, false, false, 9, '2014-01-20', 'admin', false),
  ('PICOTING STITCH', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('PIGMENT PRINTING', '2045', false, false, false, true, true, false, false, 9, '2014-01-20', 'admin', false),
  ('PIN TUK', NULL, false, false, false, false, true, false, false, 9, '2018-09-29', 'SAKTHI', false),
  ('PK FOLD/INSPECTED PC', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('POCKET ATTACH', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('POCKET BATCH', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('POM POM ATTACH', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('POUCH CHECKING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('POUCH CUTTING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('POUCH STITCHING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('POWER TABLE', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('POWER TABLE 2', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('POWERTABLE RATE REVI', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('PREPARATION WORK', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('PRINTING', NULL, false, true, false, false, false, false, false, 8, '2014-01-20', 'admin', false),
  ('PRINTING BURN OUT', NULL, false, true, false, false, false, false, false, 99, '2017-09-14', 'raju', false),
  ('PRITING', NULL, false, false, true, false, false, false, false, 9, '2019-07-25', 'SAKTHI', false),
  ('PUNCHING', NULL, false, false, true, false, false, false, false, 9, '2014-01-20', 'admin', false),
  ('QUILTING', NULL, false, true, false, false, false, false, false, 9, '2014-01-20', 'admin', false),
  ('RAISING', '2041', false, true, false, false, false, false, false, 9, '2019-04-06', 'admin', false),
  ('RE PACK&COTTON BOX', NULL, false, false, false, true, false, false, false, 9, '2020-08-13', 'production', false),
  ('RE-BURNOUT WASHING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('RE-CHECKING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('REELING', NULL, false, false, true, false, false, false, false, 9, '2014-01-20', 'admin', false),
  ('REFLECTIVE PRINT', NULL, false, false, false, false, true, false, false, 9, '2020-06-22', 'Selvan', false),
  ('RE-IRONING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('RE-IRONING-2', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('RE-IRONING-3', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('RELAX DRIER', NULL, false, true, false, false, false, false, false, 9, '2014-01-20', 'admin', false),
  ('RE-PACKING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('RE-PACKING & CARTON', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('RE-PACKING(3 PCS PK)', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('RE-PACKING(5 PCS PK)', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('RE-PACKING-2', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('RE-PACKING-3', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('REWORK', NULL, false, false, false, false, true, false, false, 9, '2020-08-29', 'kalai', false),
  ('REWORK/CHECKING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('REWORK/HEMMING STITC', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('REWORK/SEWING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('REWORK[HEAT SETTING]', NULL, false, true, false, false, false, false, false, 9, '2020-10-09', 'admin', false),
  ('RFD', NULL, false, true, false, false, false, false, false, 9, '2016-10-05', 'sivakumar', true),
  ('RIB CUTTING', NULL, false, false, false, true, true, false, false, 9, '2022-07-04', 'admin', false),
  ('RIB IN-OUT', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('RIB READY', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('ROLL FUSING', NULL, false, false, false, false, true, false, false, 9, '2020-10-29', 'admin', false),
  ('ROPE', NULL, false, false, false, true, false, false, false, 99, '2018-02-06', 'RAJU', false),
  ('ROPE ATTACH', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('ROPE ATTACHING', NULL, false, false, false, true, true, false, false, 9, '2018-07-26', 'SAKTHI', false),
  ('ROPE CENTER PEEK', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('ROPE CUTTING', NULL, false, false, false, true, true, false, false, 9, '2026-02-21', 'admin', false),
  ('ROPE EMBROIDERY', NULL, false, false, false, false, true, false, false, 99, '2017-06-20', 'SANTHANA', false),
  ('ROPE TIPPING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('ROTARY PRINTING', NULL, false, false, true, false, false, false, false, 9, '2016-10-25', 'm.prabhu', false),
  ('RUNNING S.NO CHECK', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SAMPLE IRONING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SAMPLE PACKING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SATIN FABRIC', NULL, false, false, true, false, false, false, false, 9, '2019-03-06', 'muthumani', false),
  ('SCALAPPING', NULL, false, true, false, false, false, false, false, 9, '2014-01-20', 'admin', false),
  ('SCALAPPING STITCH', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SECURITY LABLE', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SEERI', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SEERI CLOSED', NULL, false, false, false, true, false, false, false, 9, '2024-11-29', 'admin', false),
  ('SEMI BRUSHING', NULL, false, true, false, false, false, false, false, 9, '2023-12-14', 'admin', false),
  ('SEQENCE FILLED PATCH WORK', '2094', false, false, false, false, true, false, false, 9, '2019-06-04', 'SELVAN', false),
  ('SEQUEINS EMBROIDERY', NULL, false, false, false, false, true, false, false, 9, '2016-10-19', 'm.prabhu', false),
  ('SEQUENCE EMBROIDERY', NULL, false, false, false, true, false, false, false, 99, NULL, NULL, false),
  ('SEQUINS', NULL, false, false, false, true, true, false, false, 9, '2014-01-20', 'admin', false),
  ('SEWING', NULL, false, false, false, true, false, false, false, 9, '2014-01-20', 'admin', false),
  ('SHEET MAKING', NULL, false, true, false, false, false, false, false, 9, '2019-09-18', 'admin', false),
  ('SHOULDER INNER PEEK', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SIDE', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SIDE FOLDING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SIDE JOINT PANEL', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SIDE POCKET', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SINGER', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SINGER RATE REVISED', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SINGER/INHOUSE', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SIZE SEPARATION WORK', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SIZE STICKER FUSHING', NULL, false, false, false, true, true, false, false, 9, '2019-03-05', 'Balaji', false),
  ('SIZE STICKERING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SIZE STICKERING/2', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SLEEVE ATTACH', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SLEEVE CUFF ATTACH', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SLEEVE DOWER', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SLEEVE GATHERING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SLEEVE HEM', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SLEEVE PEEK', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SLEEVE SEAM', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SMOCKING', NULL, false, false, false, true, false, false, false, 9, '2023-12-02', 'admin', false),
  ('SMOKING', NULL, false, false, false, true, true, false, false, 9, '2014-01-20', 'admin', false),
  ('SNAP BUTTON', NULL, false, false, false, false, false, false, false, 99, NULL, NULL, false),
  ('SNAP BUTTON (10NOS)', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SNAP BUTTON (11NOS)', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SNAP BUTTON (12NOS', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SNAP BUTTON (13NOS)', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SNAP BUTTON (2NOS)', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SNAP BUTTON (3NOS)', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SNAP BUTTON (4NOS)', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SNAP BUTTON (5NOS)', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SNAP BUTTON (6NOS)', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SNAP BUTTON (8NOS)', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SNAP BUTTON (9NOS)', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SNAP BUTTON ATTACH', NULL, false, false, false, true, true, false, false, 9, '2014-01-20', 'admin', false),
  ('SOFTNER WASH+TUMBLE DRIER', NULL, false, true, false, false, false, false, false, 9, '2023-10-13', 'admin', false),
  ('SOULDER JOINT', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('SPIKE CUTTING', NULL, false, false, false, true, true, false, false, 9, '2021-04-23', 'admin', false),
  ('STAIN REMOVING', NULL, false, false, false, true, true, false, false, 9, '2014-01-20', 'admin', false),
  ('STEAMING', NULL, false, true, false, false, false, false, false, 9, '2014-01-20', 'admin', false),
  ('STEAMING[2 FOLD]', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('STENTERING', NULL, false, true, false, false, false, false, false, 9, '2014-01-20', 'admin', false),
  ('STENTERING+GUM CUTTING', NULL, false, true, false, false, false, false, false, 9, '2020-07-14', 'admin', false),
  ('STICKER', NULL, false, false, false, true, false, false, false, 9, '2019-08-24', 'admin', false),
  ('STICKER FUSHING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('STICKER FUSING', NULL, false, false, false, true, true, false, false, 9, '2014-01-20', 'admin', false),
  ('STICKER FUSING[SLEEV', NULL, false, false, false, true, true, false, false, 9, '2022-03-16', 'admin', false),
  ('STICKER FUSING[SLEEVE]', NULL, false, false, false, true, true, false, false, 9, '2022-03-09', 'ADMIN', false),
  ('STICKER FUSING[YOKE]', NULL, false, false, false, true, true, false, false, 9, '2022-03-09', 'ADMIN', false),
  ('STITCHING', NULL, false, false, false, true, true, false, false, 9, '2023-08-29', 'admin', false),
  ('STONE & STUD WORK', NULL, false, false, false, true, true, false, false, 9, '2014-01-20', 'admin', false),
  ('STONE ONLY', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('STONE WORK', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('STRICK OFF', NULL, false, false, false, true, true, false, false, 9, '2022-03-21', 'ADMIN', false),
  ('SUBLIMATION PRINT', NULL, false, false, false, true, true, false, false, 9, '2016-03-18', 'PRABHU', false),
  ('SUDING', NULL, false, true, false, false, false, false, false, 9, '2019-04-05', 'selvaraj', false),
  ('SUEDING', NULL, false, true, false, false, false, false, false, 9, '2014-01-20', 'admin', false),
  ('TAFFETA CUTING', NULL, false, false, false, false, true, false, false, 99, '2018-03-09', 'raju', false),
  ('TAG CHANGE', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('TAPE ATTACH', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('TAPE ATTACHING ON COMPONUNT', NULL, false, false, false, false, true, false, false, 99, '2017-02-25', 'raju', false),
  ('TAPE CALENDERING', NULL, false, true, false, false, false, false, false, 9, '2014-01-20', 'admin', false),
  ('TAPE FOLD+NECK STITC', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('TAPE SEERI ATTACH', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('THREAD/WRAPING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('TIE & DIE', NULL, false, true, false, false, false, false, false, 9, '2014-01-20', 'admin', false),
  ('TIPPING (ROPE)', NULL, false, true, false, false, false, false, false, 9, '2025-06-11', 'admin', false),
  ('TOP ELASTIC', NULL, false, false, false, false, false, false, false, 99, NULL, NULL, false),
  ('TOP&BOTTOM RECOVERY', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('TRIMMIMG', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('TRIMS DYEING', NULL, false, false, true, false, false, false, false, 9, '2014-01-20', 'admin', false),
  ('TRIMS PRINTING', NULL, false, false, true, false, false, false, false, 9, '2014-01-20', 'admin', false),
  ('TRIMS PURCHASE', NULL, false, false, true, false, false, false, false, 3, '2014-01-20', 'admin', false),
  ('TRIMS TIPPING', NULL, false, false, true, false, false, false, false, 9, '2014-01-20', 'admin', false),
  ('TRIMS WASHING', NULL, false, false, true, false, false, false, false, 9, '2016-09-20', 'm.prabhu', false),
  ('TRIMS WINDING', NULL, false, false, true, false, false, false, false, 9, '2014-01-20', 'admin', false),
  ('TRIMS WRAPING', NULL, false, false, true, false, false, false, false, 9, '2025-07-25', 'admin', false),
  ('TUMBLE DRIER', NULL, false, true, false, false, false, false, false, 9, '2023-10-11', 'admin', false),
  ('TUMBLE WASH', NULL, false, true, false, false, false, false, false, 9, '2022-09-14', 'admin', false),
  ('TWILL TAPE', NULL, false, false, true, false, false, false, false, 9, '2019-03-06', 'muthumani', false),
  ('TWISTING', NULL, true, false, false, false, false, false, false, 9, '2023-04-27', 'admin', true),
  ('UV PROTECT', NULL, false, true, false, false, false, false, false, 9, '2023-10-13', 'admin', false),
  ('V BADGE ATTACH', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('V-JOINT', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('WASH AFTER AOP', NULL, false, true, false, false, false, false, false, 9, '2016-05-20', 'govindharaj', false),
  ('WASHCARE LABEL ATTAC', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('WASHING', NULL, false, true, false, false, false, true, false, 7, '2014-01-20', 'admin', false),
  ('WINDING', NULL, true, false, false, false, false, false, false, 9, '2019-04-05', 'govindharaj', false),
  ('WINDING (ROPE)', NULL, false, true, false, false, false, false, false, 9, '2025-06-11', 'admin', false),
  ('WRAPING', NULL, false, true, false, false, false, false, false, 9, '2025-07-23', 'admin', false),
  ('YARN BLEACHING', NULL, true, false, false, false, false, false, false, 99, '2018-08-13', 'admin', false),
  ('YARN DYEING', NULL, true, false, false, false, false, false, false, 4, '2014-01-20', 'admin', false),
  ('YARN DYEING [OVER DYEING]', NULL, true, false, false, false, false, false, false, 9, '2020-08-17', 'admin', false),
  ('YARN PURCHASE', NULL, true, false, false, false, false, false, false, 1, '2014-01-20', 'admin', false),
  ('YARN TWISTING', NULL, true, false, false, false, false, false, false, 9, '2014-01-20', 'admin', true),
  ('YARN TWISTING,', NULL, true, false, false, false, false, false, false, 9, '2023-04-27', 'admin', false),
  ('YOKE', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('YOKE ATTACH', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('YOKE LABLE ATTACH', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('YOKE MAIN LABLE', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('YOKE MAIN LABLE & SI', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('YOKE PRINTING', NULL, false, false, false, false, true, false, false, 99, '2017-02-03', 'm.prabhu', false),
  ('ZIG ZAG', NULL, false, false, false, true, true, false, false, 9, '2014-01-20', 'admin', false),
  ('ZIP ATTACH', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('ZIP ATTACHING', NULL, false, false, false, true, true, false, false, 9, '2014-01-20', 'admin', false),
  ('ZIP FOLDING', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('ZIP PULLER', NULL, false, false, false, false, false, false, false, 9, NULL, NULL, false),
  ('ZIPPER BATCH WORK', NULL, false, false, false, true, false, false, false, 9, '2025-02-27', 'admin', false),
  ('ZIPPER MALT TUB ATTACH', NULL, false, false, false, true, false, false, false, 9, '2024-11-29', 'admin', false),
  ('ZIPPER PLATING', NULL, false, false, true, false, false, false, false, 9, '2023-09-15', 'admin', false)
) as v(
  name, hsn_code, for_yarn, for_fabric, for_trims, for_garments, for_components,
  has_sub_categories, designwise_delivery, sl_no, created_dt, created_by, blocked
)
where not exists (
  select 1 from public.processes existing where existing.name = v.name
);
