-- ============================================================================
-- Raagam ERP — 0296 Master Data ▸ Materials ▸ Components: legacy data sync
-- Backfills `public.components` from the legacy EDP2 "Components - U2"
-- report export (685 rows). Idempotent — guarded per-row by
-- `where not exists` on short_name, so re-running this migration is a no-op.
--
-- The rows already present (COMBED-unrelated: 'COMBED' etc. do not apply
-- here) with matching short_name are skipped by the guard.
--
-- 4 rows (LEG, LEG CUFF, BACK LEFT LEG, BACK RIGHT LEG) have
-- all_coordinates = false in the legacy report but the report does not
-- include the itemized Coordinates child-grid, so component_coordinates is
-- left empty for them — can be filled in later via the UI if needed.
--
-- Legacy data trusted verbatim: near-duplicate/typo short names (e.g.
-- "APPILIQUE EMBRIODERY" vs "APPILQUE EMBRIODERY") and rows where
-- Short Name and Description genuinely differ (e.g. 'COMPONENT' /
-- 'GIRLS T-SHIRT', 'NECK' / 'NECK RIB') are imported as-is, no cleanup.
-- ============================================================================

insert into public.components (short_name, description, all_coordinates, blocked, created_at, created_by)
select v.short_name, v.description, v.all_coordinates, v.blocked,
       coalesce(v.created_at::timestamptz, now()), v.created_by
from (values
  ('-', '-', true, false, null, null),
  ('.', '.', true, false, null, null),
  ('10', '10', true, false, null, null),
  ('100%', '100%', true, false, null, null),
  ('100% cotton', '100% cotton', true, false, null, null),
  ('3D WAVE JERSEY', '3D WAVE JERSEY', true, false, date '2024-03-24', 'MALAICHAMY'),
  ('a', 'a', true, false, null, null),
  ('ACID WASH', 'ACID WASH', true, false, null, null),
  ('ALL BODY', 'ALL BODY', true, false, null, null),
  ('all over', 'all over', true, false, null, null),
  ('all parts', 'all parts', true, false, null, null),
  ('allover', 'allover', true, false, null, null),
  ('allovwe', 'allovwe', true, false, null, null),
  ('allower', 'allower', true, false, null, null),
  ('AOP', 'AOP', true, false, date '2024-06-28', 'ADMIN'),
  ('AOP BIT PRINTING', 'AOP BIT PRINTING', true, false, null, null),
  ('AOP BITS', 'AOP BITS', true, false, null, null),
  ('aop printing', 'aop printing', true, false, null, null),
  ('AOP SUBLIMATION PRINT APPLIQUE', 'AOP SUBLIMATION PRINT APPLIQUE', true, false, date '2023-12-20', 'THEEPAN RAJ'),
  ('APPILIQUE EMBRIODERY', 'APPILIQUE EMBRIODERY', true, false, null, null),
  ('APPILQUE EMBRIODERY', 'APPILQUE EMBRIODERY', true, false, null, null),
  ('APPLIQUE', 'APPLIQUE', true, false, date '2019-09-18', 'Selvan'),
  ('APPLIQUE 1', 'APPLIQUE 1', true, false, date '2020-05-20', 'nandhakumar'),
  ('APPLIQUE EMMBRIODERY', 'APPLIQUE EMMBRIODERY', true, false, null, null),
  ('APPLIQUE1', 'APPLIQUE1', true, false, date '2020-07-30', 'Selvan'),
  ('APPLIQUE2', 'APPLIQUE2', true, false, date '2020-07-30', 'Selvan'),
  ('APPLIQUE3', 'APPLIQUE3', true, false, date '2020-07-30', 'Selvan'),
  ('APPLIQUE4', 'APPLIQUE4', true, false, date '2020-07-30', 'Selvan'),
  ('APPLIQUE5', 'APPLIQUE5', true, false, date '2020-07-30', 'Selvan'),
  ('APPLIQUE6', 'APPLIQUE6', true, false, date '2021-03-12', 'MANOJ'),
  ('APPLIQUE7', 'APPLIQUE7', true, false, date '2021-10-22', 'RADHAKANTH'),
  ('APPLIQUE8', 'APPLIQUE8', true, false, date '2021-10-22', 'RADHAKANTH'),
  ('APPPIQUE EMBRIODERY', 'APPPIQUE EMBRIODERY', true, false, null, null),
  ('ARMHOLE', 'ARMHOLE', true, false, date '2023-11-17', 'Rambabu'),
  ('BACK', 'BACK', true, false, date '2019-03-19', 'sarvan'),
  ('back & sleeve', 'back & sleeve', true, false, null, null),
  ('back bit', 'back bit', true, false, null, null),
  ('BACK BITS', 'BACK BITS', true, false, null, null),
  ('BACK BODY', 'BACK BODY', true, false, date '2016-03-07', 'admin'),
  ('BACK BODY + SLEEVE + BINDING', 'BACK BODY + SLEEVE + BINDING', true, false, date '2017-03-03', 'RAJU'),
  ('BACK BODY 2', 'BACK BODY 2', true, false, date '2023-03-10', 'santhosh'),
  ('BACK BODY AND SLEEVE', 'BACK BODY AND SLEEVE', true, false, date '2016-03-12', 'admin'),
  ('BACK BODY BACK INNR .', 'BACK BODY BACK INNR .', true, false, date '2018-03-30', 'SAKTHI'),
  ('BACK BODY BOTTOM', 'BACK BODY BOTTOM', true, false, date '2016-03-18', 'admin'),
  ('BACK BODY BOTTOM INNER', 'BACK BODY BOTTOM INNER', true, false, date '2017-08-31', 'raju'),
  ('BACK BODY INNER', 'BACK BODY INNER', true, false, date '2017-08-31', 'raju'),
  ('BACK BODY LEFT', 'BACK BODY LEFT', true, false, date '2016-04-19', 'Raju'),
  ('BACK BODY RIGHT', 'BACK BODY RIGHT', true, false, date '2016-04-19', 'Raju'),
  ('BACK BODY TOP', 'BACK BODY TOP', true, false, date '2016-03-18', 'admin'),
  ('BACK BODY TOP PANEL', 'BACK BODY TOP PANEL', true, false, date '2017-09-18', 'raju'),
  ('BACK BODY TOP PANEL (INNER)', 'BACK BODY TOP PANEL (INNER)', true, false, date '2017-09-18', 'raju'),
  ('BACK BODY TOP+BOTTOM', 'BACK BODY TOP+BOTTOM', true, false, date '2018-02-23', 'm.prabhu'),
  ('BACK BODY+ SLEEVE+ BACK YOKE', 'BACK BODY+ SLEEVE+ BACK YOKE', true, false, date '2016-05-25', 'sakthivel'),
  ('BACK BODY+BACK SLEEVE PANEL', 'BACK BODY+BACK SLEEVE PANEL', true, false, date '2019-11-17', 'Selvan'),
  ('BACK BODY+FRONT BODY LEFT+LEFT SLEEVE', 'BACK BODY+FRONT BODY LEFT+LEFT SLEEVE', true, false, date '2017-10-30', 'SENDURAPANDI'),
  ('BACK BODY+FRONT BODY+NECK BIND+SLEEVE1', 'BACK BODY+FRONT BODY+NECK BIND+SLEEVE1', true, false, date '2017-09-30', 'raju'),
  ('BACK BODY+FRONT TOP PANEL', 'BACK BODY+FRONT TOP PANEL', true, false, date '2017-08-12', 'raju'),
  ('BACK BODY+NECK BINDING', 'BACK BODY+NECK BINDING', true, false, date '2019-09-18', 'Selvan'),
  ('BACK BODY+NECK TAPE', 'BACK BODY+NECK TAPE', true, false, date '2017-09-05', 'm.prabhu'),
  ('BACK BODY+PLACKET', 'BACK BODY+PLACKET', true, false, date '2019-10-04', 'Selvan'),
  ('BACK BODY+PLACKET+NECK BINDING', 'BACK BODY+PLACKET+NECK BINDING', true, false, date '2016-10-19', 'm.prabhu'),
  ('BACK BODY+RIGHT SLEEVE+FRONT RIGHT', 'BACK BODY+RIGHT SLEEVE+FRONT RIGHT', true, false, date '2017-10-30', 'SENDURAPANDI'),
  ('BACK BODY+SLEEVE', 'BACK BODY+SLEEVE', true, false, date '2017-09-26', 'SENDURAPANDI'),
  ('BACK BODY+SLEEVE+', 'BACK BODY+SLEEVE+SLEEVE INSERT+NECK TAPE+PIPING', true, false, date '2016-07-08', 'm.prabhu'),
  ('BACK BODY+SLEEVE+ HOOD OUTER', 'BACK BODY+SLEEVE+ HOOD OUTER', true, false, date '2016-05-25', 'sakthivel'),
  ('BACK BODY+SLEEVE+HOOD', 'BACK BODY+SLEEVE+HOOD', true, false, date '2017-09-26', 'SENDURAPANDI'),
  ('BACK BODY+SLEEVE+NECK RIB+NECK TAPE', 'BACK BODY+SLEEVE+NECK RIB+NECK TAPE', true, false, date '2019-07-19', 'SELVAN'),
  ('BACK BODY+SLEEVE+NECK TAPE', 'BACK BODY+SLEEVE+NECK TAPE', true, false, date '2017-02-18', 'm.prabhu'),
  ('BACK BODY+SLEEVE+NECK TAPE+BINDING', 'BACK BODY+SLEEVE+NECK TAPE+BINDING', true, false, date '2018-07-21', 'm.prabhu'),
  ('BACK BODY+SLEEVE+NECK TAPE+PLACKET', 'BACK BODY+SLEEVE+NECK TAPE+PLACKET', true, false, date '2018-05-04', 'm.prabhu'),
  ('BACK BODY+SLEEVE+PLACKET', 'BACK BODY+SLEEVE+PLACKET', true, false, date '2019-10-09', 'Selvan'),
  ('BACK BODY+SLEEVE+PLACKET+CROTCH', 'BACK BODY+SLEEVE+PLACKET+CROTCH', true, false, date '2018-07-13', 'm.prabhu'),
  ('BACK BODY+SLEEVE+PLACKET+PIPING', 'BACK BODY+SLEEVE+PLACKET', true, false, date '2016-12-23', 'm.prabhu'),
  ('BACK BODY+SLEEVE+POCKET', 'BACK BODY+SLEEVE+POCKET', true, false, date '2017-09-26', 'SENDURAPANDI'),
  ('BACK BODY+SLEEVE+SHOULDER PLACKET', 'BACK BODY+SLEEVE+SHOULDER PLACKET', true, false, date '2018-07-28', 'm.prabhu'),
  ('BACK BODY+SLEEVE+SLEEVE FRILLS', 'BACK BODY+SLEEVE+SLEEVE FRILLS', true, false, date '2018-02-15', 'm.prabhu'),
  ('BACK BODY+SLEEVE+SLEEVE SEAM BINDING', 'BACK BODY+SLEEVE+SLEEVE SEAM BINDING', true, false, date '2018-07-28', 'm.prabhu'),
  ('BACK BODY+SLEEVE1', 'BACK BODY+SLEEVE1', true, false, date '2019-09-24', 'Selvan'),
  ('BACK BODY+SLV+NECK BINDING+PIPING', 'BACK BODY+SLV+NECK BINDING+PIPING', true, false, date '2017-07-25', 'RAJU'),
  ('BACK BODY+SLV+SLV FRILL+BTM FRILL', 'BACK BODY+SLV+SLV FRILL+BTM FRILL', true, false, date '2020-07-28', 'chandru'),
  ('BACK BODY+SLV+SLV INSERT+NECKTAPE+PIPING', 'BACK BODY+SLV+SLV INSERT+NECKTAPE+PIPING', true, false, date '2016-07-08', 'm.prabhu'),
  ('BACK BOTTOM 1', 'BACK BOTTOM 1', true, false, date '2017-09-14', 'raju'),
  ('BACK BOTTOM 2', 'BACK BOTTOM 2', true, false, date '2017-09-14', 'raju'),
  ('BACK BOTTOM+FRONT RIGHT TOP', 'BACK BOTTOM +FRONT RIGHT TOP', true, false, date '2017-08-23', 'RAJU'),
  ('BACK CUT & SEWN - 1', 'BACK CUT & SEWN - 1', true, false, date '2018-07-20', 'SAKTHI'),
  ('BACK CUT & SEWN - 2', 'BACK CUT & SEWN - 2', true, false, date '2018-07-20', 'SAKTHI'),
  ('BACK CUT & SEWN -1', 'BACK CUT & SEWN -1', true, false, date '2018-07-31', 'SAKTHI'),
  ('BACK CUT & SEWN -2', 'BACK CUT & SEWN -2', true, false, date '2018-07-31', 'SAKTHI'),
  ('BACK CUT & SEWN -3', 'BACK CUT & SEWN -3', true, false, date '2018-07-31', 'SAKTHI'),
  ('BACK CUT & SEWN -4', 'BACK CUT & SEWN -4', true, false, date '2018-07-31', 'SAKTHI'),
  ('BACK CUT & SEWN -5', 'BACK CUT 1', true, false, date '2018-07-31', 'SAKTHI'),
  ('BACK CUT 1', 'BACK CUT 1', true, false, date '2019-07-23', 'Nandhakumar'),
  ('BACK CUT 2', 'BACK CUT 2', true, false, date '2018-03-17', 'SAKTHI'),
  ('BACK CUT 3', 'BACK CUT 3', true, false, date '2018-03-17', 'SAKTHI'),
  ('BACK INNER AND CUT PANEL', 'BACKT INNER AND CUT PANEL', true, false, date '2018-03-17', 'SAKTHI'),
  ('BACK LEFT LEG', 'BACK LEFT LEG', false, false, date '2016-06-11', 'M.Prabhu'),
  ('BACK LEG TOP', 'BACK LEG TOP', true, false, date '2019-08-09', 'SAKTHI'),
  ('BACK NACK BATCH', 'BACK NACK BATCH', true, false, date '2017-09-12', 'raju'),
  ('BACK NECK', 'BACK NECK', true, false, date '2017-08-08', 'Balaji'),
  ('BACK NECK PATCH', 'BACK NECK PATCH', true, false, date '2017-09-12', 'raju'),
  ('BACK PANEL 1', 'BACK PANEL 1', true, false, date '2023-03-11', 'santhosh'),
  ('BACK PANEL BOTTOM 1', 'BACK PANEL BOTTOM 1', true, false, date '2023-12-09', 'santhosh'),
  ('BACK PANEL BOTTOM 2', 'BACK PANEL BOTTOM 2', true, false, date '2023-12-09', 'santhosh'),
  ('BACK PANEL TOP', 'BACK PANEL TOP', true, false, date '2023-12-09', 'santhosh'),
  ('BACK POCKET', 'BACK POCKET', true, false, date '2020-10-27', 'Selvan'),
  ('BACK RIGHT LEG', 'BACK RIGHT LEG', false, false, date '2016-06-11', 'M.Prabhu'),
  ('BACK YOKE', 'BACK YOKE', true, false, null, null),
  ('BACK+NECK BINDING', 'BACK+NECK BINDING', true, false, date '2017-08-24', 'RAJU'),
  ('BACK+NECK PIPING', 'BACK+NECK PIPING', true, false, date '2017-08-12', 'raju'),
  ('BAG BACK PANEL', 'BAG BACK PANEL', true, false, date '2019-12-06', 'mohan'),
  ('BAG FRONT', 'BAG FRONT', true, false, date '2019-12-06', 'mohan'),
  ('base', 'base', true, false, null, null),
  ('bbits', 'bbits', true, false, null, null),
  ('BELT', 'BELT', true, false, date '2016-04-19', 'Raju'),
  ('BELT SOLID', 'BELT SOLID', true, false, date '2023-12-09', 'santhosh'),
  ('biits', 'biits', true, false, null, null),
  ('BINDING', 'BINDING', true, false, date '2017-03-02', 'RAJU'),
  ('BIO WASH', 'BIO WASH', true, false, null, null),
  ('Bio washing', 'Bio washing', true, false, null, null),
  ('bis', 'bis', true, false, null, null),
  ('BIST', 'BIST', true, false, null, null),
  ('bit', 'bit', true, false, null, null),
  ('bit''', 'bit''', true, false, null, null),
  ('BIT EMBRIODERY', 'BIT EMBRIODERY', true, false, null, null),
  ('BIT EMB', 'BIT EMB', true, false, null, null),
  ('BIT EMBOSSING', 'BIT EMBOSSING', true, false, null, null),
  ('bit embossing.', 'bit embossing.', true, false, null, null),
  ('BIT EMBRIOIDERY', 'BIT EMBRIOIDERY', true, false, null, null),
  ('bit print', 'bit print', true, false, null, null),
  ('BIT PRINTING', 'BIT PRINTING', true, false, null, null),
  ('BIT PRINTING FRONT', 'BIT PRINTING FRONT', true, false, null, null),
  ('bit priting', 'bit priting', true, false, null, null),
  ('BIT WASH', 'BIT WASH', true, false, null, null),
  ('BIT WASHING', 'BIT WASHING', true, false, null, null),
  ('bit.', 'bit.', true, false, null, null),
  ('BITS', 'BITS', true, false, null, null),
  ('BITS (S/J &RIB)', 'BITS (S/J &RIB)', true, false, null, null),
  ('BITS RFD', 'BITS RFD', true, false, null, null),
  ('BITS.', 'BITS.', true, false, null, null),
  ('bitss', 'bitss', true, false, null, null),
  ('BKITS', 'BKITS', true, false, null, null),
  ('BLACK BITS', 'BLACK BITS', true, false, null, null),
  ('BODY', 'BODY', true, false, date '2016-03-07', 'admin'),
  ('BODY LAYER-1', 'BODY LAYER-1', true, false, date '2024-06-08', 'malaichamy'),
  ('BODY LAYER-2', 'BODY LAYER-2', true, false, date '2024-06-08', 'malaichamy'),
  ('BODY LAYER-3', 'BODY LAYER-3', true, false, date '2024-06-08', 'malaichamy'),
  ('BODY+NECK RIB+NECK TAPE', 'BODY+NECK RIB+NECK TAPE', true, false, date '2023-11-24', 'Rambabu'),
  ('BODY+NK RIB+NK TAPE', 'BODY+NK RIB+NK TAPE', true, false, date '2023-11-22', 'Rambabu'),
  ('BODY+PATTY+N.SEERI+SLV PIPPING', 'BODY+PATTY+N.SEERI+SLV PIPPING', true, false, date '2023-07-13', 'govintharaj'),
  ('BODY-BOTTOM', 'BODY-BOTTOM', true, false, date '2024-03-24', 'MALAICHAMY'),
  ('BODY-BOTTOM-2', 'BODY-BOTTOM-2', true, false, date '2024-03-24', 'MALAICHAMY'),
  ('BODY-TOP', 'BODY-TOP', true, false, date '2024-03-24', 'MALAICHAMY'),
  ('BODY-TOP-2', 'BODY-TOP-2', true, false, date '2024-03-24', 'MALAICHAMY'),
  ('boits', 'boits', true, false, null, null),
  ('BOTTOM', 'BOTTOM', true, false, date '2017-07-26', 'SANTHANA'),
  ('BOTTOM & CUFF', 'BOTTOM & CUFF', true, false, date '2016-04-19', 'Raju'),
  ('BOTTOM + CUFF + NECK RIB', 'BOTTOM + CUFF + NECK RIB', true, false, date '2025-07-02', 'DHANDAPANI'),
  ('BOTTOM + SLEEVE + NECK RIB', 'BOTTOM + SLEEVE + NECK RIB', true, false, date '2016-06-04', 'sakthivel'),
  ('BOTTOM + SLEEVE PANEL', 'BOTTOM + SLEEVE PANEL', true, false, date '2018-02-06', 'raju'),
  ('BOTTOM BACK', 'BOTTOM BACK', true, false, date '2018-06-13', 'SAKTHI'),
  ('BOTTOM BINDING', 'BOTTOM BINDING', true, false, date '2016-08-05', 'RAJU'),
  ('BOTTOM BITS', 'BOTTOM BITS', true, false, null, null),
  ('BOTTOM CUFF', 'BOTTOM CUFF', true, false, date '2016-04-29', 'RAJU'),
  ('BOTTOM CUFF RIB', 'BOTTOM CUFF RIB', true, false, date '2016-05-21', 'sakthivel'),
  ('BOTTOM CUT 1', 'BOTTOM CUT 1', true, false, date '2018-04-11', 'SAKTHI'),
  ('BOTTOM CUT 2', 'BOTTOM CUT 2', true, false, date '2018-04-11', 'SAKTHI'),
  ('BOTTOM CUT 3', 'BOTTOM CUT 3', true, false, date '2018-04-11', 'SAKTHI'),
  ('BOTTOM CUT 4', 'BOTTOM CUT 4', true, false, date '2018-04-11', 'SAKTHI'),
  ('BOTTOM FOLDING', 'BOTTOM FOLDING', true, false, date '2020-09-05', 'admin'),
  ('BOTTOM FRIL PHANEL FRONT & BACK', 'BOTTOM FRIL PHANEL FRONT & BACK', true, false, date '2018-03-27', 'sakthi'),
  ('BOTTOM FRONT', 'BOTTOM FRONT', true, false, date '2019-11-24', 'mohan'),
  ('BOTTOM FRONT,BACK+SLEEVE PANEL', 'BOTTOM FRONT,BACK+SLEEVE PANEL', true, false, date '2019-11-17', 'Selvan'),
  ('BOTTOM FRONT+BACK+SLEEVE', 'BOTTOM FRONT+BACK+SLEEVE PANEL', true, false, date '2019-11-17', 'Selvan'),
  ('BOTTOM INNER', 'BOTTOM INNER', true, false, date '2017-03-02', 'RAJU'),
  ('bottom left panel', 'bottom left panel', true, false, null, null),
  ('BOTTOM PANEL', 'BOTTOM PANEL', true, false, date '2016-03-18', 'PRABHU'),
  ('BOTTOM PANEL (INSIDE)', 'BOTTOM PANEL (INSIDE)', true, false, date '2016-08-05', 'RAJU'),
  ('BOTTOM PANEL 1', 'BOTTOM PANEL 1', true, false, date '2016-04-26', 'raju'),
  ('BOTTOM PANEL 2', 'BOTTOM PANEL 2', true, false, date '2016-04-26', 'raju'),
  ('BOTTOM PANEL-2', 'BOTTOM PANEL-2', true, false, null, null),
  ('BOTTOM PANEL-4', 'BOTTOM PANEL-4', true, false, null, null),
  ('BOTTOM RIB', 'BOTTOM RIB', true, false, date '2017-02-27', 'RAJU'),
  ('BOTTOM RIB+CUFF RIB', 'BOTTOM RIB+CUFF RIB', true, false, date '2023-09-18', 'santhosh'),
  ('BOTTOM SLIT FOLDING', 'BOTTOM SLIT FOLDING', true, false, date '2017-09-14', 'raju'),
  ('BOTTOM+CUFF+NECK', 'BOTTOM+CUFF+NECK', true, false, date '2017-09-26', 'SENDURAPANDI'),
  ('BOTTOM-Front', 'BOTTOM-Front', true, false, null, null),
  ('BOW', 'BOW', true, false, date '2018-07-28', 'm.prabhu'),
  ('BTMFRONTBODY+BTMBACKBODY+BTMSLVE+SLVE C1', 'BTM FRONT BODY+BTM BACK BODY+BTM SLEEVE+SLEEVE CUT1', true, false, date '2019-08-10', 'Selvan'),
  ('CHAMBRAY', 'CHAMBRAY', true, false, date '2024-03-24', 'MALAICHAMY'),
  ('coconut milk', 'coconut milk', true, false, null, null),
  ('colla,sleeve', 'colla,sleeve', true, false, null, null),
  ('COLLAR', 'COLLAR', true, false, date '2017-06-17', 'santhana'),
  ('COLLAR AND CUFF', 'COLLAR AND CUFF', true, false, date '2019-07-05', 'Nandhakumar'),
  ('COLLAR LAYER-1', 'COLLAR LAYER-1', true, false, date '2024-06-08', 'malaichamy'),
  ('COLLAR LAYER-2', 'COLLAR LAYER-2', true, false, date '2024-06-08', 'malaichamy'),
  ('COLLAR LAYER-3', 'COLLAR LAYER-3', true, false, date '2024-06-08', 'malaichamy'),
  ('COLLAR STAND', 'COLLAR STAND', true, false, date '2023-10-25', 'SANTHOSH'),
  ('collar,sleeve', 'collar,sleeve', true, false, null, null),
  ('COLLAR+NECK BINDING', 'COLLAR+NECK BINDING', true, false, date '2023-11-17', 'Rambabu'),
  ('COLLAR+YOCK+PATTY', 'COLLAR+YOCK+PATTY', true, false, date '2023-11-20', 'Rambabu'),
  ('COMPONENT', 'GIRLS T-SHIRT', true, false, date '2017-02-25', 'raju'),
  ('coton', 'coton', true, false, null, null),
  ('cotton', 'cotton', true, false, null, null),
  ('CPL WASING', 'CPL WASING', true, false, null, null),
  ('CPL WASHING', 'CPL WASHING', true, false, null, null),
  ('cream', 'cream', true, false, null, null),
  ('ctn', 'ctn', true, false, null, null),
  ('CUFF RIB', 'CUFF RIB', true, false, date '2016-03-12', 'admin'),
  ('CUFF+BOTTOM', 'CUFF+BOTTOM', true, false, date '2018-07-28', 'm.prabhu'),
  ('cut', 'cut', true, false, null, null),
  ('CUT & SEWN RIGHT', 'CUT & SEWN RIGHT', true, false, date '2017-09-14', 'raju'),
  ('CUT PANELS', 'CUT PANELS', true, false, null, null),
  ('DIP DYE', 'DIP DYE', true, false, null, null),
  ('Dip dyeing', 'Dip dyeing', true, false, null, null),
  ('EARS', 'EARS', true, false, date '2020-09-03', 'admin'),
  ('emb', 'emb', true, false, null, null),
  ('EMB APPLIQUE 1', 'EMB APPLIQUE 1', true, false, date '2016-05-26', 'sakthivel'),
  ('EMB APPLIQUE 2', 'EMB APPLIQUE 2', true, false, date '2016-05-26', 'sakthivel'),
  ('EMB APPLIQUE 3', 'EMB APPLIQUE 3', true, false, date '2019-07-11', 'sowmiyaraj'),
  ('EMB APPLIQUE 4', 'EMB APPLIQUE 4', true, false, date '2019-07-11', 'sowmiyaraj'),
  ('EMB APPLIQUE 5', 'EMB APPLIQUE 5', true, false, date '2019-07-11', 'sowmiyaraj'),
  ('EMB APPLIQUE 6', 'EMB APPLIQUE 6', true, false, date '2019-07-11', 'sowmiyaraj'),
  ('EMB APPLIQUE -7', 'EMB APPLIQUE -7', true, false, date '2019-07-18', 'SOWMIYARAJ'),
  ('embriodery', 'embriodery', true, false, null, null),
  ('EMBROIDERY APPLIQUE', 'EMBROIDERY APPLIQUE', true, false, date '2017-02-25', 'RAJU'),
  ('EMP APLIC', 'EMP APLIC', true, false, date '2016-03-26', 'admin'),
  ('F', 'F', true, false, null, null),
  ('FABRIC', 'FABRIC', true, false, null, null),
  ('FFRONT CUT & SEWN-1', 'FFRONT CUT & SEWN-1', true, false, date '2018-07-31', 'SAKTHI'),
  ('FFRONT CUT & SEWN-2', 'FFRONT CUT & SEWN-2', true, false, date '2018-07-31', 'SAKTHI'),
  ('FFRONT CUT & SEWN-3', 'FFRONT CUT & SEWN-3', true, false, date '2018-07-31', 'SAKTHI'),
  ('FFRONT CUT & SEWN-4', 'FFRONT CUT & SEWN-4', true, false, date '2018-07-31', 'SAKTHI'),
  ('FFRONT CUT & SEWN-5', 'FFRONT CUT & SEWN-5', true, false, date '2018-07-31', 'SAKTHI'),
  ('FINISHED', 'FINISHED', true, false, null, null),
  ('FINISHING', 'FINISHING', true, false, null, null),
  ('FINISHING PCS', 'FINISHING PCS', true, false, null, null),
  ('finshing pcs', 'finshing pcs', true, false, null, null),
  ('FLOUNCE', 'FRONT & BACK FLOUNCE', true, false, date '2021-11-01', 'MUTHURAJ'),
  ('FOLDING', 'FOLDING', true, false, date '2016-08-05', 'RAJU'),
  ('FOOT', 'FOOT', true, false, date '2020-09-05', 'admin'),
  ('fornt', 'fornt', true, false, null, null),
  ('fr', 'fr', true, false, null, null),
  ('FRILL', 'FRILL', true, false, date '2020-09-05', 'admin'),
  ('Frint & Back bits', 'Frint & Back bits', true, false, null, null),
  ('FRNT+BACK+SIDE PCKS+WAIST BAND+BACK PCKT', 'FRNT+BACK+SIDE PCKS+WAIST BAND+BACK PCKT', true, false, date '2025-11-26', 'dhandapani'),
  ('FRNT+BACK+SLV+IN& OUT HOOD+SINGLE POCKET', 'FRNT+BACK+SLV+IN& OUT HOOD+SINGLE POCKET', true, false, date '2025-08-27', 'DHANDAPANI'),
  ('FRON BODY RIGHT+BACK BODY RIGHT', 'FRON BODY RIGHT+BACK BODY RIGHT+RIGHT SLEEVE', true, false, date '2017-09-26', 'SENDURAPANDI'),
  ('fron t', 'fron t', true, false, null, null),
  ('FRONT', 'FRONT', true, false, date '2017-12-29', 'kalingaraj'),
  ('FRONT & BACK', 'FRONT & BACK', true, false, null, null),
  ('FRONT & BACK BODY+NECK TAPE', 'FRONT & BACK BODY+NECK TAPE', true, false, date '2019-09-12', 'Selvan'),
  ('FRONT & BACK FLOUNCE', 'FRONT & BACK FLOUNCE', true, false, date '2021-11-01', 'MUTHURAJ'),
  ('front \back', 'front \back', true, false, null, null),
  ('FRONT + BACK + ARMHOLE & NECK PIPEING', 'FRONT + BACK + ARMHOLE & NECK PIPEING', true, false, date '2018-08-12', 'SAKTHI'),
  ('FRONT + BACK + LOWER POCKET', 'FRONT + BACK + LOWER POCKET', true, false, date '2025-07-02', 'DHANDAPANI'),
  ('FRONT + BACK + SIDE POCKETS +BACK POCKET', 'FRONT + BACK + SIDE POCKETS +BACK POCKET', true, false, date '2025-07-03', 'DHANDAPANI'),
  ('FRONT + BACK + SLEEVE + HOODY INNER & O', 'FRONT + BACK + SLEEVE + HOODY INNER & OUTER + POCKET', true, false, date '2024-10-16', 'admin'),
  ('FRONT + BACK + SLEEVE + PIPING', 'FRONT + BACK + SLEEVE + PIPING', true, false, date '2017-12-29', 'kalingaraj'),
  ('FRONT + BACK + SLEEVE + SIDE PANELS', 'FRONT + BACK + SLEEVE + SIDE PANELS', true, false, date '2025-07-02', 'DHANDAPANI'),
  ('FRONT + BACK LEG', 'FRONT + BACK LEG', true, false, date '2016-06-04', 'sakthivel'),
  ('FRONT +BACK BOTTOM PANEL', 'FRONT +BACK BOTTOM PANEL', true, false, date '2017-08-13', 'RAJU'),
  ('front 1', 'front 1', true, false, null, null),
  ('FRONT 1 + SLEEVE + BACK + NECK', 'FRONT 1 + SLEEVE + BACK + NECK', true, false, date '2021-09-29', 'muthuraj'),
  ('front 2', 'front 2', true, false, null, null),
  ('FRONT 2 + NECK BINDING', 'FRONT 2 + NECK BINDING', true, false, date '2021-09-29', 'muthuraj'),
  ('front 3', 'front 3', true, false, null, null),
  ('front 4', 'front 4', true, false, null, null),
  ('front all ver', 'front all ver', true, false, null, null),
  ('FRONT AND BACK IN TUBULAR', 'FRONT AND BACK IN TUBULAR', true, false, date '2019-02-22', 'Balaji'),
  ('front and back print', 'front and back print', true, false, null, null),
  ('FRONT AND SLEEVE', 'FRONT AND SLEEVE', true, false, null, null),
  ('FRONT BACK ARM HOLE AND SLV PIPING', 'FRONT + BACK +ARM HOLE PIPING + NECK PIPING', true, false, date '2018-08-12', 'SAKTHI'),
  ('front back bit', 'front back bit', true, false, null, null),
  ('FRONT BIT', 'FRONT BIT', true, false, null, null),
  ('front bits', 'front bits', true, false, null, null),
  ('FRONT BODY', 'FRONT BODY', true, false, date '2016-03-07', 'admin'),
  ('FRONT BODY + BACK BODY', 'FRONT BODY + BACK BODY', true, false, date '2016-06-06', 'sakthivel'),
  ('FRONT BODY +BACK BODY+BINDING', 'FRONT BODY +BACK BODY+BINDING', true, false, date '2019-07-18', 'SELVAN'),
  ('FRONT BODY +BACK BODY+SLEEVE +POCKET', 'FRONT BODY +BACK BODY+SLEEVE +POCKET', true, false, date '2017-07-01', 'SANTHANA'),
  ('FRONT BODY +BACK BODY+SLV', 'FRONT BODY +BACK BODY+SLV', true, false, date '2016-05-20', 'sakthivel'),
  ('FRONT BODY BACK INNER', 'FRONT BODY BACK INNER', true, false, date '2017-08-31', 'raju'),
  ('FRONT BODY BACK TOP', 'FRONT BODY BACK TOP', true, false, date '2018-09-17', 'SAKTHI'),
  ('FRONT BODY BOTTOM', 'FRONT BODY BOTTOM', true, false, date '2016-03-17', 'raju'),
  ('FRONT BODY BOTTOM CENTRE', 'FRONT BODY BOTTOM CENTRE', true, false, date '2017-08-23', 'RAJU'),
  ('FRONT BODY BOTTOM INNER', 'FRONT BODY BOTTOM INNER', true, false, date '2017-08-31', 'raju'),
  ('FRONT BODY BOTTOM LEFT', 'FRONT BODY BOTTOM LEFT', true, false, date '2017-08-23', 'RAJU'),
  ('FRONT BODY BOTTOM PORTION', 'FRONT BODY BOTTOM PORTION', true, false, date '2017-08-12', 'raju'),
  ('FRONT BODY BOTTOM RIGHT', 'FRONT BODY BOTTOM RIGHT', true, false, date '2017-08-23', 'RAJU'),
  ('FRONT BODY FRILL', 'FRONT BODY FRILL', true, false, date '2019-07-26', 'Nandhakumar'),
  ('FRONT BODY FRONT INNER', 'FRONT BODY FRONT INNER', true, false, date '2018-03-01', 'SAKTHI'),
  ('FRONT BODY LEFT', 'FRONT BODY LEFT', true, false, date '2016-03-18', 'PRABHU'),
  ('FRONT BODY LEFT+BACK BODY LEFT', 'FRONT BODY LEFT+BACK BODY LEFT+LEFT SLEEVE', true, false, date '2017-09-26', 'SENDURAPANDI'),
  ('FRONT BODY LEFT+BACK BODY LEFT+SLEEVE', 'FRONT BODY LEFT+BACK BODY LEFT+SLEEVE', true, false, date '2017-09-26', 'SENDURAPANDI'),
  ('FRONT BODY LEFT+BACK BODY+LEFT SLEEVE', 'FRONT BODY LEFT+BACK BODY+LEFT SLEEVE +LEFT HOOD', true, false, date '2017-10-30', 'SENDURAPANDI'),
  ('FRONT BODY LEFT+LEFT SLEEVE', 'FRONT BODY LEFT+LEFT SLEEVE', true, false, date '2017-10-30', 'SENDURAPANDI'),
  ('FRONT BODY LEFT+LEFT SLEEVE+BACK BODY', 'FRONT BODY LEFT+LEFT SLEEVE+BACK BODY', true, false, date '2017-10-30', 'SENDURAPANDI'),
  ('FRONT BODY OUTER PANNEL', 'FRONT BODY OUTER PANNEL', true, false, date '2017-09-01', 'raju'),
  ('FRONT BODY RIGHT', 'FRONT BODY RIGHT', true, false, date '2016-03-18', 'PRABHU'),
  ('FRONT BODY RIGHT +RIGHT SLEEVE', 'FRONT BODY RIGHT +RIGHT SLEEVE', true, false, date '2017-10-30', 'SENDURAPANDI'),
  ('FRONT BODY RIGHT TOP', 'FRONT BODY RIGHT TOP', true, false, date '2017-08-23', 'RAJU'),
  ('FRONT BODY RIGHT+BACK BODY RIGHT', 'FRONT BODY RIGHT+BACK BODY RIGHT', true, false, date '2017-09-26', 'SENDURAPANDI'),
  ('FRONT BODY RIGHT+BACK BODY RIGHT+SLEEVE', 'FRONT BODY RIGHT+BACK BODY RIGHT+SLEEVE', true, false, date '2017-09-26', 'SENDURAPANDI'),
  ('FRONT BODY RIGHT+RIGHT SLEEVE', 'FRONT BODY RIGHT+RIGHT SLEEVE+HOOD RIGHT', true, false, date '2017-10-30', 'SENDURAPANDI'),
  ('FRONT BODY RIGHT+RIGHT SLEEVE+RIGHT HOOD', 'FRONT BODY RIGHT+RIGHT SLEEVE+RIGHT HOOD', true, false, date '2017-10-30', 'SENDURAPANDI'),
  ('FRONT BODY TOP', 'FRONT BODY TOP', true, false, date '2016-03-17', 'raju'),
  ('FRONT BODY TOP +BOTTOM+SLEEVE', 'FRONT BODY TOP +BOTTOM+SLEEVE', true, false, date '2018-02-23', 'm.prabhu'),
  ('FRONT BODY TOP INNER', 'FRONT BODY TOP INNER', true, false, date '2017-08-31', 'raju'),
  ('FRONT BODY TOP LEFT', 'FRONT BODY TOP LEFT', true, false, date '2017-08-23', 'RAJU'),
  ('FRONT BODY TOP OUTER', 'FRONT BODY TOP OUTER', true, false, date '2017-09-01', 'raju'),
  ('FRONT BODY TOP+BOTTOM&BACK BODY TOP+BOTT', 'FRONT BODY TOP+BOTTOM&BACK BODY TOP+BOTTOM', true, false, date '2018-02-23', 'm.prabhu'),
  ('FRONT BODY/LEFT', 'FRONT BODY/LEFT', true, false, date '2020-11-30', 'rajesh'),
  ('FRONT BODY/RIGHT', 'FRONT BODY/RIGHT', true, false, date '2020-11-30', 'rajesh'),
  ('FRONT BODY+ARM HOLE BINDING', 'FRONT BODY+ARM HOLE BINDING', true, false, date '2017-09-18', 'raju'),
  ('FRONT BODY+BACK BODY +SLEEVE+HOOD', 'FRONT BODY+BACK BODY +SLEEVE+HOOD', true, false, date '2017-07-01', 'SANTHANA'),
  ('FRONT BODY+BACK BODY+BINDING', 'FRONT BODY+BACK BODY+BINDING', true, false, date '2018-09-29', 'm.prabhu'),
  ('FRONT BODY+BACK BODY+BOTTOM LACE', 'FRONT BODY+BACK BODY+BOTTOM LACE', true, false, date '2019-10-12', 'selvan'),
  ('FRONT BODY+BACK BODY+NECK,ARM BINDING', 'FRONT BODY+BACK BODY+NECK ,ARM BINDING', true, false, date '2019-09-07', 'Selvan'),
  ('FRONT BODY+BACK BODY+POCKET', 'FRONT BODY+BACK BODY+POCKET', true, false, date '2018-09-22', 'm.prabhu'),
  ('FRONT BODY+BACK BODY+SLEEVE', 'FRONT BODY+BACK BODY+SLEEVE', true, false, date '2018-02-23', 'm.prabhu'),
  ('FRONT BODY+BACK BODY+SLEEVE+BINDING', 'FRONT BODY+BACK BODY+SLEEVE+BINDING', true, false, date '2019-08-31', 'Selvan'),
  ('FRONT BODY+BACK BODY+SLEEVE+NECK RIB', 'FRONT BODY+BACK BODY+SLEEVE+NECK RIB', true, false, date '2019-08-05', 'SELVAN'),
  ('FRONT BODY+BACK BODY+SLEEVE+NECK TAPE', 'FRONT BODY+BACK BODY+SLEEVE+NECK TAPE', true, false, date '2018-11-09', 'm.prabhu'),
  ('FRONT BODY+NECK BINDING', 'FRONT BODY+NECK BINDING', true, false, date '2021-09-28', 'muthuraj'),
  ('FRONT BODY1', 'FRONT BODY1', true, false, date '2019-09-24', 'Selvan'),
  ('FRONT BOTTOM 1', 'FRONT BOTTOM 1', true, false, date '2017-09-14', 'raju'),
  ('FRONT BOTTOM 2', 'FRONT BOTTOM 2', true, false, date '2017-09-14', 'raju'),
  ('FRONT BOTTOM PANEL', 'FRONT BOTTOM PANEL', true, false, date '2021-02-06', 'RADHAKANTH'),
  ('FRONT BOTTOM PANEL+BACK BOTTOM PANEL', 'FRONT BOTTOM PANEL+BACK BOTTOM PANEL', true, false, date '2019-08-01', 'SELVAN'),
  ('FRONT BOTTOM PANNEL', 'FRONT BOTTOM PANNEL', true, false, date '2021-07-31', 'MANOJ'),
  ('FRONT BOTTOM+BACK BOTTOM', 'FRONT BOTTOM+BACK BOTTOM', true, false, date '2018-09-29', 'm.prabhu'),
  ('FRONT CUT - 2', 'FRONT CUT - 2', true, false, date '2018-07-26', 'SAKTHI'),
  ('FRONT CUT - 3', 'FRONT CUT - 3', true, false, date '2018-07-26', 'SAKTHI'),
  ('FRONT CUT & SEW 1 + BACK BODY + SLEEVE', 'FRONT CUT & SEW 1 + BACK BODY + SLEEVE', true, false, date '2021-01-30', 'RADHAKANTH'),
  ('FRONT CUT & SEW PANEL', 'FRONT CUT & SEW PANEL', true, false, date '2019-08-01', 'SELVAN'),
  ('FRONT CUT -1', 'FRONT CUT -1', true, false, date '2018-07-26', 'SAKTHI'),
  ('FRONT CUT PANEL', 'FRONT CUT PANEL', true, false, null, null),
  ('FRONT CUT+ BACK CUT PANNEL', 'FRONT CUT+ BACK CUT PANNEL', true, false, date '2022-03-04', 'muthuraj'),
  ('FRONT FOLDING', 'FRONT FOLDING', true, false, date '2023-03-11', 'santhosh'),
  ('FRONT INNER OUTER +BACK INNER OUTER', 'FRONT INNER OUTER +BACK INNER OUTER', true, false, date '2017-08-13', 'raju'),
  ('FRONT INSIDE & NECK INSIDE PANEL', 'FRONT INSIDE & NECK INSIDE PANEL', true, false, date '2023-12-09', 'santhosh'),
  ('FRONT LEFT BOTTOM', 'FRNT LEFT BOTTOM', true, false, date '2023-12-09', 'santhosh'),
  ('FRONT LEFT BOTTOM & LEFT SLEEVE CUFF', 'FRONT LEFT BOTTOM & LEFT SLEEVE CUFF', true, false, date '2017-11-01', 'SENDURAPANDI'),
  ('FRONT LEFT LEG', 'FRONT LEFT LEG', true, false, date '2016-03-07', 'admin'),
  ('FRONT LEFT TOP', 'FRONT LEFT TOP', true, false, date '2023-12-09', 'santhosh'),
  ('FRONT LEG TOP', 'FRONT LEG TOP', true, false, date '2019-08-09', 'SAKTHI'),
  ('FRONT LEG+BACK LEG', 'FRONT LEG+BACK LEG', true, false, date '2018-02-23', 'm.prabhu'),
  ('FRONT MIDDLE PANEL', 'FRONT MIDDLE PANEL', true, false, date '2021-02-06', 'RADHAKANTH'),
  ('FRONT MIDDLE PANEL+BACK MIDDLE PANEL', 'FRONT MIDDLE PANEL+BACK MIDDLE PANEL', true, false, date '2019-08-01', 'SELVAN'),
  ('FRONT MIDDLE PANNEL+BACK PANNEL', 'FRONT MIDDLE PANNEL+BACK PANNEL', true, false, date '2021-07-31', 'MANOJ'),
  ('FRONT NECK', 'FRONT NECK', true, false, date '2017-08-08', 'Balaji'),
  ('FRONT OUTER', 'FRONT OUTER', true, false, date '2018-07-18', 'SAKTHI'),
  ('FRONT PANEL 1', 'FRONT PANEL 1', true, false, date '2023-03-11', 'santhosh'),
  ('FRONT PANEL TOP+BACK PANEL TOP', 'FRONT PANEL TOP+BACK PANEL TOP', true, false, date '2019-07-18', 'SELVAN'),
  ('FRONT RIGHT BOTTOM', 'FRONT RIGHT BOTTOM', true, false, date '2023-12-09', 'santhosh'),
  ('FRONT RIGHT LEG', 'FRONT RIGHT LEG', true, false, date '2016-03-26', 'Balaji'),
  ('FRONT RIGHT LEG+BACK', 'FRONT RIGHT LEG+BACK', true, false, date '2019-01-04', 'Balaji'),
  ('FRONT RIGHT TOP', 'FRONT RIGHT TOP', true, false, date '2023-12-09', 'santhosh'),
  ('FRONT RIGHT+BACK BOTTOM+RIGHT SLEEVE CUF', 'FRONT RIGHT+BACK BOTTOM+RIGHT SLEEVE CUF', true, false, date '2017-11-01', 'SENDURAPANDI'),
  ('FRONT TOP PANEL', 'FRONT TOP PANEL', true, false, date '2021-07-31', 'MANOJ'),
  ('FRONT TOP PANEL+BACK TOP PANEL+SLEEVE', 'FRONT TOP PANEL+BACK TOP PANEL+SLEEVE', true, false, date '2019-08-01', 'SELVAN'),
  ('FRONT TOP PANEL+BACK TOP PANEL+SLEEVE+NT', 'FRONT TOP PANEL+BACK TOP PANEL+SLEEVE+NE', true, false, date '2019-08-01', 'SELVAN'),
  ('FRONT TOP+BACK TOP+LEAF+BINDING', 'FRONT TOP+BACK TOP+LEAF+BINDING', true, false, date '2018-09-29', 'm.prabhu'),
  ('FRONT&BACK', 'FRONT BODY+BACK BODY', true, false, date '2019-10-04', 'selvan'),
  ('front&back&slv', 'front&back&slv', true, false, null, null),
  ('FRONT(RE-113)', 'FRONT(RE-113)', true, false, null, null),
  ('FRONT, BACK', 'FRONT, BACK', true, false, null, null),
  ('FRONT/BACK', 'FRONT/BACK', true, false, null, null),
  ('front/back/sleeve bit', 'front/back/sleeve bit', true, false, null, null),
  ('FRONT+ BACK LEG', 'FRONT+ BACK LEG', true, false, date '2016-05-21', 'sakthivel'),
  ('FRONT+BACK BODY+POCKET+WASITBAND', 'FRONT+BACK BODY+POCKET+WASITBAND', true, false, date '2019-10-05', 'Selvan'),
  ('FRONT+BACK BODY+SLEEVE+FLOUNCE1+FLOUNCE2', 'FRONT+BACK BODY+SLEEVE+FLOUNCE1+FLOUNCE2', true, false, date '2018-02-19', 'm.prabhu'),
  ('FRONT+BACK BODY+SLEEVE+FRONT+BACK FLOUNC', 'FRONT+BACK BODY+SLEEVE+FRONT+BACK FLOUNCE', true, false, date '2017-08-10', 'm.prabhu'),
  ('FRONT+BACK BODY+SLEEVE+NECK BINDING', 'FRONT+BACK BODY+SLEEVE+NECK BINDING', true, false, date '2019-08-10', 'Selvan'),
  ('FRONT+BACK BODY+SLEEVE+NECK TAPE', 'FRONT+BACK BODY+SLEEVE+NECK TAPE', true, false, date '2017-09-13', 'm.prabhu'),
  ('FRONT+BACK BODY+SLEEVE+NECK TAPE+BINDING', 'FRONT+BACK BODY+SLEEVE+NECK TAPE+BINDING', true, false, date '2017-09-13', 'm.prabhu'),
  ('FRONT+BACK BODY+SLEEVE+PLACKET', 'FRONT+BACK BODY+SLEEVE+PLACKET', true, false, date '2019-10-05', 'Selvan'),
  ('FRONT+BACK BODY+SLEEVE+PLACKET+NECK TAPE', 'FRONT+BACK BODY+SLEEVE+PLACKET+NECK TAPE', true, false, date '2019-10-01', 'Selvan'),
  ('FRONT+BACK+2 PANEL', 'FRONT+BACK+2 PANEL', true, false, date '2017-08-13', 'raju'),
  ('FRONT+BACK+BACK NECK STRAP', 'FRONT+BACK+BACK NECK STRAP', true, false, date '2017-08-13', 'raju'),
  ('FRONT+BACK+BACK POCKET', 'FRONT+BACK+BACK POCKET', true, false, date '2026-04-14', 'dhandapani'),
  ('FRONT+BACK+FRNTPOCKET+WAIST+BACK POCKET', 'FRONT+BACK+FRNTPOCKET+WAIST+BACK POCKET', true, false, date '2026-04-14', 'dhandapani'),
  ('FRONT+BACK+HOOD', 'FRONT+BACK+HOOD', true, false, date '2017-07-05', 'SANTHANA'),
  ('FRONT+BACK+LEAF+BINDING', 'FRONT+BACK+LEAF+BINDING', true, false, date '2018-09-29', 'm.prabhu'),
  ('FRONT+BACK+NECK BINDING+BRIDAL WORK', 'FRONT+BACK+NECK BINDING+BRIDAL WORK', true, false, date '2018-09-29', 'm.prabhu'),
  ('FRONT+BACK+SLEEVE', 'FRONT+BACK+SLEEVE', true, false, date '2016-05-21', 'sakthivel'),
  ('FRONT+BACK+SLEEVE+HOOD', 'FRONT+BACK+SLEEVE+HOOD', true, false, date '2017-07-16', 'SANTHANA'),
  ('FRONT+BACK+SLEEVE+INNER SLEEVE', 'FRONT+BACK+SLEEVE+INNER SLEEVE', true, false, date '2017-08-13', 'raju'),
  ('FRONT+BACK+SLEEVE+NECK PIPING & BINDING', 'FRONT+BACK+SLEEVE+NECK PIPING & BINDING', true, false, date '2018-06-07', 'sakthi'),
  ('FRONT+BACK+SLEEVE+PLACKET+NECK BINDING', 'FRONT+BACK+SLEEVE+PLACKET+NECK BINDING', true, false, date '2017-02-03', 'm.prabhu'),
  ('FRONT+BACK+SLEEVE+POCKET', 'FRONT+BACK+SLEEVE+POCKET', true, false, date '2017-07-19', 'SANTHANA'),
  ('FRONT+BACK+SLEEVE+SKIRT', 'FRONT+BACK+SLEEVE+SKIRT', true, false, date '2025-12-22', 'dhandapani'),
  ('FRONT+BACK+SLV+NECK', 'FRONT+BACK+SLV+NECK', true, false, date '2023-12-25', 'Rambabu'),
  ('FRONT+BACK+SLV+NECK TAPE+BINDING+KEYHOLE', 'FRONT+BACK+SLV+NECK TAPE+BINDING+KEYHOLE', true, false, date '2018-07-21', 'm.prabhu'),
  ('FRONT+BACK+SLV+POCKET+HOOD', 'FRONT+BACK+SLV+POCKET+HOOD', true, false, date '2017-07-05', 'SANTHANA'),
  ('FRONT+BACK+SLV+YOCK', 'FRONT+BACK+SLV+YOCK', true, false, date '2023-11-20', 'Rambabu'),
  ('FRONT+BACK+WAIST', 'FRONT+BACK+WAIST', true, false, date '2026-04-14', 'dhandapani'),
  ('FRONT+BACK+WASTBAND+POCKET+FRILL+BOW', 'FRONT+BACK+WASTBAND+POCKET+FRILL+BOW', true, false, date '2019-10-05', 'selvan'),
  ('FRONT+SLEEVE', 'FRONT+SLEEVE', true, false, date '2017-08-12', 'raju'),
  ('front3', 'front3', true, false, null, null),
  ('full body', 'full body', true, false, null, null),
  ('GARMENT', 'GARMENT', true, false, null, null),
  ('GARMENT DYE', 'GARMENT DYE', true, false, null, null),
  ('GARMENT DYEING', 'GARMENT DYEING', true, false, null, null),
  ('GARMENT DYEING PURPOSES', 'GARMENT DYEING PURPOSES', true, false, null, null),
  ('garment printing', 'garment printing', true, false, null, null),
  ('garment washing', 'garment washing', true, false, null, null),
  ('GARMENTS', 'GARMENTS', true, false, null, null),
  ('GARMRNTS', 'GARMRNTS', true, false, null, null),
  ('GARNENTS', 'GARNENTS', true, false, null, null),
  ('green colour', 'green colour', true, false, null, null),
  ('GUSSET', 'GUSSET', true, false, date '2020-09-05', 'admin'),
  ('HALF FINISH BITS', 'HALF FINISH BITS', true, false, null, null),
  ('HANG TAG LOOP', 'HANG TAG LOOP', true, false, date '2019-07-20', 'ranjith'),
  ('HANGER LOOP', 'HANGER LOOP', true, false, date '2019-07-13', 'ranjith'),
  ('HIGH NECK', 'HIGH NECK', true, false, date '2023-11-10', 'santhosh'),
  ('HOOD', 'HOOD', true, false, date '2016-04-19', 'Raju'),
  ('HOOD + POCKET', 'HOOD + POCKET', true, false, date '2017-09-26', 'SENDURAPANDI'),
  ('HOOD INNER', 'HOOD INNER', true, false, date '2018-03-17', 'SAKTHI'),
  ('HOOD INNER + SLEEVE STRIPES', 'HOOD INNER + SLEEVE STRIPES', true, false, date '2026-04-14', 'dhandapani'),
  ('HOOD INNER+ZIP INNER', 'HOOD INNER+ZIP INNER', true, false, date '2020-09-03', 'admin'),
  ('HOOD INSIDE', 'HOOD INSIDE', true, false, date '2016-04-19', 'Raju'),
  ('HOOD INSIDE+NECK TAPE', 'HOOD INSIDE+NECK TAPE', true, false, date '2017-09-26', 'SENDURAPANDI'),
  ('HOOD LEFT', 'HOOD LEFT', true, false, date '2017-09-26', 'SENDURAPANDI'),
  ('HOOD LEFT+SIDE POCKET', 'HOOD LEFT+SIDE POCKET', true, false, date '2017-10-30', 'SENDURAPANDI'),
  ('HOOD OUTER', 'HOOD OUTER', true, false, date '2020-11-05', 'Selvan'),
  ('HOOD RIGHT', 'HOOD RIGHT', true, false, date '2017-09-26', 'SENDURAPANDI'),
  ('HOOD RIGHT +SIDE POCKET', 'HOOD RIGHT +SIDE POCKET', true, false, date '2017-10-30', 'SENDURAPANDI'),
  ('HOOD+HOOD INEAR+POCKET', 'HOOD+HOOD INEAR+POCKET', true, false, date '2023-09-18', 'santhosh'),
  ('HOODY INNER & OUTER', 'HOODY INNER & OUTER', true, false, date '2023-12-21', 'THEEPAN RAJ'),
  ('HYPNOTIK', 'NECK/SLV/CUFF&BOTTOM', true, false, date '2017-07-04', 'SANTHANA'),
  ('INNER CUT & SEWN 1', 'INNER CUT & SEWN 1', true, false, date '2018-09-17', 'SAKTHI'),
  ('INNER CUT & SWEN 2', 'INNER CUT & SWEN 2', true, false, date '2018-09-17', 'SAKTHI'),
  ('INNER CUT & SWEN 3', 'INNER CUT & SWEN 3', true, false, date '2018-09-17', 'SAKTHI'),
  ('INNER CUT & SWEN 4', 'INNER CUT & SWEN 4', true, false, date '2018-09-17', 'SAKTHI'),
  ('INNER FLONCE', 'INNER FLONCE', true, false, date '2018-09-29', 'SAKTHI'),
  ('INNER LAYER', 'INNER LAYER', true, false, date '2019-03-01', 'Balaji'),
  ('INNER NECK BNDING', 'INER NECK BNDING', true, false, date '2018-03-27', 'sakthi'),
  ('INNER NECK PHANEL', 'INNER NECK PHANEL', true, false, date '2018-03-27', 'sakthi'),
  ('INNER NECK RIB', 'INNER NECK RIB', true, false, date '2016-05-20', 'sakthivel'),
  ('INNER NECK RIB + V BATCH', 'INNER NECK RIB + V BATCH', true, false, date '2016-05-20', 'sakthivel'),
  ('INNER NECK RIB+NECK TAPE+YOKE', 'INNER NECK RIB+NECK TAPE+YOKE', true, false, date '2019-11-17', 'Selvan'),
  ('INNER RIB+NECK RIB+YOKE', 'INNER RIB+NECK RIB+YOKE', true, false, date '2019-11-17', 'Selvan'),
  ('INNER SLEEVE & FOLDING', 'INNER SLEEVE & FOLDING', true, false, date '2018-07-30', 'SAKTHI'),
  ('JERSEY PATCH', 'JERSEY PATCH', true, false, date '2016-12-23', 'm.prabhu'),
  ('KANGAROO POCKET', 'KANGAROO POCKET', true, false, date '2023-12-21', 'THEEPAN RAJ'),
  ('KEY HOLE', 'KEY HOLE', true, false, date '2019-07-13', 'ranjith'),
  ('KGS', 'KGS', true, false, null, null),
  ('left bottom panel', 'left bottom panel', true, false, null, null),
  ('LEFT PATCH', 'LEFT PATCH', true, false, date '2017-07-05', 'SANTHANA'),
  ('LEFT SIDE PANNEL', 'LEFT SIDE PANNEL', true, false, date '2019-02-13', 'SAKTHI'),
  ('LEFT SIDE POCKET', 'LEFT SIDE POCKET', true, false, date '2017-04-08', 'Balaji'),
  ('LEFT SLEEVE', 'LEFT SLEEVE', true, false, date '2019-08-22', 'SAKTHI'),
  ('LEFT SLEEVE CUT& SEW PANEL1', 'LEFT SLEEVE CUT& SEW PANEL1', true, false, date '2019-08-10', 'Selvan'),
  ('LEFT SLEEVE+FRONT BODY LEFT', 'LEFT SLEEVE+FRONT BODY LEFT', true, false, date '2017-10-30', 'SENDURAPANDI'),
  ('LEFT&RIGHT SIDE PANEL', 'LEFT&RIGHT SIDE PANEL', true, false, date '2017-07-11', 'SANTHANA'),
  ('LEG', 'LEG', false, false, date '2016-06-11', 'admin'),
  ('LEG CUFF', 'LEG CUFF', false, false, date '2016-06-11', 'admin'),
  ('LEG LEFT CUFF', 'CUFF', true, false, date '2017-04-08', 'Balaji'),
  ('LEG RIGHT CUFF', 'CUFF', true, false, date '2017-04-08', 'Balaji'),
  ('LINNING FABRIC', 'LINNING FABRIC', true, false, date '2019-08-13', 'SAKTHI'),
  ('LOOPER', 'LOOPER', true, false, date '2018-02-19', 'M.PRABHU'),
  ('MAIN BODY', 'MAIN BODY', true, false, date '2016-03-12', 'admin'),
  ('mask', 'mask', true, false, null, null),
  ('METER', 'METER', true, false, null, null),
  ('MIDDLE FOLDING', 'MIDDLE FOLDING', true, false, date '2020-05-27', 'Nandhakumar'),
  ('MIDDLE FOLING', 'MIDDLE FOLING', true, false, date '2020-05-27', 'Nandhakumar'),
  ('MOBILE POCKET', 'MOBILE POCKET', true, false, date '2022-05-26', 'SUNDAR'),
  ('NECK', 'NECK RIB', true, false, date '2016-04-23', 'Balaji'),
  ('NECK & ARM HOLE BINDING', 'NECK & ARM HOLE BINDING', true, false, date '2017-09-14', 'raju'),
  ('NECK & SLV PIPING', 'NECK & SLV PIPING', true, false, date '2020-08-27', 'admin'),
  ('NECK & SPLIT FOLDING', 'NECK & SPLIT FOLDING', true, false, date '2018-07-30', 'SAKTHI'),
  ('NECK + SLEEVE + BOTTOM = RIB', 'NECK + SLEEVE + BOTTOM = RIB', true, false, date '2019-09-05', 'SAKTHI'),
  ('NECK + SLEEVE BOTTOM RIB', 'NECK + SLEEVE BOTTOM RIB', true, false, date '2019-02-22', 'Balaji'),
  ('NECK + SLEEVE FOLDING', 'NECK + SLEEVE FOLDING', true, false, date '2017-02-27', 'RAJU'),
  ('NECK + SLEEVE TRIM', 'NECK + SLEEVE TRIM', true, false, date '2023-10-24', 'SANTHOSH'),
  ('NECK +ARM HOLE FOLDING', 'NECK +ARM HOLE FOLDING', true, false, date '2017-08-12', 'raju'),
  ('NECK +BOTTOM +SLEEVE = CUFF', 'NECK +BOTTOM +SLEEVE = CUFF', true, false, date '2018-07-31', 'SAKTHI'),
  ('NECK AND ARMHOLE BINDING', 'NECK AND ARMHOLE BINDING', true, false, date '2018-01-25', 'RAJU'),
  ('NECK AND CUFF', 'NECK AND CUFF', true, false, date '2016-03-19', 'Balaji'),
  ('NECK APPLIQUE', 'NECK APPLIQUE', true, false, date '2018-06-13', 'SAKTHI'),
  ('NECK BATCH', 'NECK BATCH', true, false, date '2018-07-30', 'SAKTHI'),
  ('NECK BELT 1', 'NECK BELT 1', true, false, date '2016-07-14', 'RAJU'),
  ('NECK BELT 2', 'NECK BELT 2', true, false, date '2016-07-14', 'RAJU'),
  ('NECK BELT 3', 'NECK BELT 3', true, false, date '2016-07-14', 'RAJU'),
  ('NECK BINDING', 'NECK BINDING', true, false, date '2016-03-07', 'admin'),
  ('NECK BINDING + ZIPPER FACING', 'NECK BINDING + ZIPPER FACING', true, false, date '2025-08-18', 'dhandapani'),
  ('NECK BINDING+SLEEVE BINDING', 'NECK BINDING+SLEEVE BINDING', true, false, date '2019-08-05', 'SELVAN'),
  ('NECK BINDING1', 'NECK BINDING1', true, false, date '2019-09-24', 'Selvan'),
  ('NECK FOLDING', 'NECK FOLDING', true, false, date '2016-04-19', 'Raju'),
  ('NECK FRILL', 'NECK FRILL', true, false, date '2019-06-27', 'SELVAN'),
  ('NECK PIPEING', 'NECK PIPEING', true, false, date '2018-08-28', 'SAKTHI'),
  ('NECK PIPING', 'NECK PIPING', true, false, date '2019-07-23', 'Nandhakumar'),
  ('NECK PIPING +NECK BINDING', 'NECK PIPING +NECK BINDING', true, false, date '2018-06-07', 'sakthi'),
  ('NECK RIB', 'NECK RIB', true, false, date '2016-03-07', 'admin'),
  ('NECK RIB +SLEEVE RIB= CUFF', 'NECK RIB +SLEEVE RIB= CUFF', true, false, date '2019-07-11', 'sowmiyaraj'),
  ('NECK RIB/CUFF/BOTTOM', 'NECK RIB/CUFF/BOTTOM', true, false, date '2017-07-12', 'SANTHANA'),
  ('NECK RIB+NECK TAPE', 'NECK RIB+NECK TAPE', true, false, date '2023-11-24', 'Rambabu'),
  ('NECK RIB+NET FOLDING+NECK TAPE', 'NECK RIB+NET FOLDING+NECK TAPE', true, false, date '2023-09-18', 'santhosh'),
  ('NECK RIB+SLEEVE CUFF RIB', 'NECK RIB+SLEEVE CUFF RIB', true, false, date '2019-09-25', 'Selvan'),
  ('NECK RIB+SLEEVE CUFF RIB+BOTTOM RIB', 'NECK RIB+SLEEVE CUFF RIB+BOTTOM RIB', true, false, date '2019-08-01', 'SELVAN'),
  ('NECK SEERI', 'NECK SEERI', true, false, date '2017-10-31', 'SANTHANA'),
  ('NECK TAPE', 'NECK TAPE', true, false, date '2016-07-05', 'm.prabhu'),
  ('NECK TAPE + ZIPPER BINDING', 'NECK TAPE + ZIPPER BINDING', true, false, date '2022-10-10', 'santhosh'),
  ('NECK TAPE(AROUND NECK)', 'NECK TAPE(AROUND NECK)', true, false, date '2023-11-10', 'santhosh'),
  ('NECK TAPE+NECK RIB', 'NECK TAPE+NECK RIB', true, false, date '2023-09-21', 'santhosh'),
  ('NECK TAPE+SLIT', 'NECK TAPE+SLIT', true, false, date '2019-08-05', 'SELVAN'),
  ('NECK TRIM', 'NECK TRIM', true, false, date '2023-10-24', 'SANTHOSH'),
  ('neck yoke', 'neck yoke', true, false, null, null),
  ('NECK/SLV/CUFF&BOTTOM', 'NECK/SLV/CUFF&BOTTOM', true, false, date '2017-07-04', 'SANTHANA'),
  ('NECK+SLEEVE RIB', 'NECK+SLEEVE RIB', true, true, date '2017-08-13', 'raju'),
  ('NECK+SLV BINDING', 'NECK+SLV BINDING', true, false, date '2016-08-05', 'RAJU'),
  ('NET FOLDING', 'NET FOLDING', true, false, date '2023-09-18', 'santhosh'),
  ('NET FOLDING+NECK TAPE+NECK RIB', 'NET FOLDING+NECK TAPE+NECK RIB', true, false, date '2023-09-18', 'santhosh'),
  ('NITS', 'NITS', true, false, null, null),
  ('OFF FINISHING', 'OFF FINISHING', true, false, null, null),
  ('OUTER LAYER', 'OUTER LAYER', true, false, date '2018-04-30', 'Balaji'),
  ('OUTER NECK RIB', 'OUTER NECK RIB', true, false, date '2016-05-20', 'sakthivel'),
  ('OUTER NECK RIB + V BATCH', 'OUTER NECK RIB + V BATCH', true, false, date '2016-07-25', 'm.prabhu'),
  ('p', 'p', true, false, null, null),
  ('PANEL', 'PANEL', true, false, null, null),
  ('pant bit with rib', 'pant bit with rib', true, false, null, null),
  ('PANT FRONT+BACK', 'PANT FRONT+BACK BODY', true, false, date '2020-07-03', 'Selvan'),
  ('PANT NET FOLDING', 'PANT NET FOLDING', true, false, date '2023-03-11', 'santhosh'),
  ('pcs', 'pcs', true, false, null, null),
  ('Pcs & Bits', 'Pcs & Bits', true, false, null, null),
  ('Pcs/Bits', 'Pcs/Bits', true, false, null, null),
  ('PCS''S', 'PCS''S', true, false, null, null),
  ('PICES', 'PICES', true, false, null, null),
  ('pieces', 'pieces', true, false, null, null),
  ('piecs', 'piecs', true, false, null, null),
  ('pink', 'pink', true, false, null, null),
  ('PIPING', 'PIPING', true, false, date '2017-03-16', 'm.prabhu'),
  ('PIPING 1', 'PIPING 1', true, false, date '2019-03-01', 'Balaji'),
  ('PIPING 2', 'PIPING 2', true, false, date '2019-03-01', 'Balaji'),
  ('PITS', 'PITS', true, false, null, null),
  ('PLACKET', 'PLACKET', true, false, date '2017-03-21', 'Balaji'),
  ('PLACKET 1', 'PLACKET 1', true, false, date '2023-09-25', 'santhosh'),
  ('PLACKET -2', 'PLACKET -2', true, false, date '2019-11-24', 'mohan'),
  ('PLACKET PIPING', 'PLACKET PIPING', true, false, date '2019-07-02', 'nandhakumar'),
  ('PLACKET+YOKE', 'PLACKET+YOKE', true, false, date '2023-09-22', 'santhosh'),
  ('POCKET', 'POCKET', true, false, date '2016-03-07', 'admin'),
  ('pocket and front', 'pocket and front', true, false, null, null),
  ('POCKET BINDING', 'POCKET BINDING', true, false, date '2025-11-27', 'dhandapani'),
  ('POCKET INNER', 'POCKET INNER', true, false, date '2023-02-23', 'ADMIN'),
  ('POCKET+ HOOD INNER', 'POCKET+ HOOD INNER', true, false, date '2016-05-26', 'sakthivel'),
  ('POCKET+NECK TAPE', 'POCKET+NECK TAPE', true, false, date '2023-12-01', 'santhosh'),
  ('poly', 'poly', true, false, null, null),
  ('pr', 'pr', true, false, null, null),
  ('prin', 'prin', true, false, null, null),
  ('printing', 'printing', true, false, null, null),
  ('PRINTING PURPOSES', 'PRINTING PURPOSES', true, false, null, null),
  ('PURPLE', 'PURPLE', true, false, null, null),
  ('Reprocess', 'Reprocess', true, false, null, null),
  ('REWORK', 'REWORK', true, false, null, null),
  ('RIB AT SLEEVE CUFF AND BOTTOM AND NECK', 'RIB AT SLEEVE CUFF AND BOTTOM AND NECK', true, false, date '2018-02-15', 'm.prabhu'),
  ('RIGHT LEG', 'RIGHT LEG', true, false, null, null),
  ('RIGHT SIDE PANNEL', 'RIGHT SIDE PANNEL', true, false, date '2019-02-13', 'SAKTHI'),
  ('RIGHT SIDE POCKET', 'RIGHT SIDE POCKET', true, false, date '2017-04-08', 'Balaji'),
  ('RIGHT SLEEVE', 'RIGHT SLEEVE', true, false, date '2019-08-22', 'SAKTHI'),
  ('RIGHT SLEEVE CUT& SEW PANEL1', 'RIGHT SLEEVE CUT& SEW PANEL1', true, false, date '2019-08-10', 'Selvan'),
  ('RIGHT SLEEVE+FRONT BODY RIGHT+BACK BODY', 'RIGHT SLEEVE+FRONT BODY RIGHT+BACK BODY', true, false, date '2017-10-30', 'SENDURAPANDI'),
  ('Roll', 'Roll', true, false, null, null),
  ('S/J & RIB BITS', 'S/J & RIB BITS', true, false, null, null),
  ('S/J,RIB,COLLAR', 'S/J,RIB,COLLAR', true, false, null, null),
  ('SCARP', 'SCARP', true, false, null, null),
  ('SEMI FINIFHED', 'SEMI FINIFHED', true, false, null, null),
  ('SHORTS', 'SHORTS', true, false, null, null),
  ('shorts aop', 'shorts aop', true, false, null, null),
  ('SHOULDER LACE', 'SHOULDER LACE', true, false, date '2022-12-08', 'SUNDAR'),
  ('SHOULDER PANEL', 'SHOULDER PANEL', true, false, date '2016-08-05', 'RAJU'),
  ('SHOULDER PANEL 2 PARTS', 'SHOULDER PANEL 2 PARTS', true, false, date '2023-10-24', 'SANTHOSH'),
  ('side', 'side', true, false, null, null),
  ('SIDE CUT & SEWN LEFT', 'SIDE CUT & SEWN LEFT', true, false, date '2017-09-14', 'raju'),
  ('SIDE CUT & SEWN RIGHT', 'SIDE CUT & SEWN RIGHT', true, false, date '2018-03-01', 'SAKTHI'),
  ('SIDE PANEL', 'SIDE PANEL', true, false, date '2016-09-21', 'RAJU'),
  ('SIDE PATCH', 'SIDE PATCH', true, false, date '2017-07-05', 'SANTHANA'),
  ('SIDE POCKET', 'SIDE POCKET', true, false, date '2019-01-04', 'Balaji'),
  ('SIDE SLIT', 'SIDE SLIT', true, false, date '2020-08-22', 'admin'),
  ('SILICON WASH', 'SILICON WASH', true, false, null, null),
  ('skirt', 'skirt', true, false, null, null),
  ('SKIRT+SHORT+WAIST BAND', 'SKIRT+SHORT+WAIST BAND', true, false, date '2025-11-27', 'dhandapani'),
  ('SLEEVE', 'SLEEVE', true, false, date '2016-03-07', 'admin'),
  ('SLEEVE & BOTTOM CUT 2', 'SLEEVE & BOTTOM CUT 2', true, false, date '2018-03-17', 'SAKTHI'),
  ('SLEEVE & BOTTOM RIB', 'SLEEVE & BOTTOM RIB', true, false, date '2019-07-25', 'SAKTHI'),
  ('SLEEVE & NECK & BOTTON RIB', 'SLEEVE & NECK & BOTTON RIB', true, false, date '2018-03-29', 'SAKTHI'),
  ('SLEEVE + BOTTOM RIB', 'SLEEVE + BOTTOM RIB', true, false, date '2018-01-29', 'raju'),
  ('SLEEVE + NECK = RIB', 'SLEEVE + NECK = RIB', true, false, date '2019-08-10', 'SOWMIYARAJ'),
  ('SLEEVE + NECK TAPE', 'SLEEVE + NECK TAPE', true, false, date '2022-10-08', 'santhosh'),
  ('SLEEVE + V BATCH', 'SLEEVE + V BATCH', true, false, date '2016-05-26', 'sakthivel'),
  ('SLEEVE + YOKE', 'SLEEVE + YOKE', true, false, date '2023-10-25', 'SANTHOSH'),
  ('SLEEVE 1', 'SLEEVE 1', true, false, date '2017-03-02', 'RAJU'),
  ('SLEEVE 2', 'SLEEVE 2', true, false, date '2017-03-02', 'RAJU'),
  ('SLEEVE AND BOTTOM CUFF', 'SLEEVE AND BOTTOM CUFF', true, false, date '2019-01-14', 'Balaji'),
  ('SLEEVE AND NECK BINDING', 'SLEEVE AND NECK BINDING', true, false, date '2018-04-26', 'SAKTHI'),
  ('sleeve aop', 'sleeve aop', true, false, null, null),
  ('SLEEVE BINDING', 'SLEEVE BINDING', true, false, date '2016-08-05', 'RAJU'),
  ('SLEEVE CUFF', 'SLEEVE CUFF', true, false, date '2016-04-29', 'RAJU'),
  ('SLEEVE CUFF RIB+ V BATCH RIB', 'SLEEVE CUFF RIB+ V BATCH RIB', true, false, date '2016-05-26', 'sakthivel'),
  ('SLEEVE CUFF RIB+BTM RIB', 'SLEEVE CUFF RIB+BTM RIB', true, false, date '2020-07-03', 'Selvan'),
  ('SLEEVE CUFF1', 'SLEEVE CUFF1', true, false, date '2019-08-07', 'SELVAN'),
  ('SLEEVE CUT - 1', 'SLEEVE CUT - 1', true, false, date '2018-07-20', 'SAKTHI'),
  ('SLEEVE CUT - 2', 'SLEEVE CUT - 2', true, false, date '2018-07-20', 'SAKTHI'),
  ('SLEEVE CUT - 3', 'SLEEVE CUT - 3', true, false, date '2018-07-20', 'SAKTHI'),
  ('SLEEVE CUT 2+FRONT SIDE PANEL+PIPING', 'SLEEVE CUT 2+FRONT SIDE PANEL+PIPING', true, false, date '2021-09-28', 'muthuraj'),
  ('SLEEVE CUT 2+PIPING', 'SLEEVE CUT 2+PIPING', true, false, date '2021-09-28', 'muthuraj'),
  ('SLEEVE CUT PANEL', 'SLEEVE CUT PANEL', true, false, date '2018-03-17', 'SAKTHI'),
  ('SLEEVE EDGE LACE', 'SLEEVE EDGE LACE', true, false, date '2023-12-11', 'Rambabu'),
  ('SLEEVE INNER', 'SLEEVE INNER', true, false, date '2023-03-30', 'ershad'),
  ('SLEEVE LACE', 'SLEEVE LACE', true, false, date '2022-12-08', 'SUNDAR'),
  ('SLEEVE LAYER-1', 'SLEEVE LAYER-1', true, false, date '2024-06-08', 'malaichamy'),
  ('SLEEVE LAYER-2', 'SLEEVE LAYER-2', true, false, date '2024-06-08', 'malaichamy'),
  ('SLEEVE LAYER-3', 'SLEEVE LAYER-3', true, false, date '2024-06-08', 'malaichamy'),
  ('sleeve -left', 'sleeve -left', true, false, null, null),
  ('SLEEVE LEFT', 'SLEEVE LEFT', true, false, date '2016-07-14', 'RAJU'),
  ('SLEEVE NET FOLDING', 'SLEEVE NET FOLDING', true, false, date '2019-09-05', 'SAKTHI'),
  ('SLEEVE PANEL', 'SLEEVE PANEL', true, false, date '2016-05-03', 'RAJU'),
  ('SLEEVE PLACKET', 'SLEEVE PLACKET', true, false, date '2023-10-24', 'SANTHOSH'),
  ('SLEEVE RIB', 'SLEEVE RIB', true, false, date '2018-01-25', 'raju'),
  ('sleeve -right', 'sleeve -right', true, false, null, null),
  ('SLEEVE RIGHT', 'SLEEVE RIGHT', true, false, date '2016-07-14', 'RAJU'),
  ('SLEEVE RIGHT CUT & SEWN', 'SLEEVE RIGHT CUT & SEWN', true, false, date '2018-07-31', 'SAKTHI'),
  ('SLEEVE RUFFLES', 'SLEEVE RUFFLES', true, false, date '2017-08-12', 'raju'),
  ('SLEEVE+BOTTOM FOLDING', 'SLEEVE+BOTTOM FOLDING', true, false, date '2017-07-14', 'SANTHANA'),
  ('SLEEVE+HOOD OUTER+FRONT POCKET', 'SLEEVE+HOOD OUTER+FRONT POCKET', true, false, date '2019-01-14', 'Balaji'),
  ('SLEEVE+HOOD+PATCHES', 'SLEEVE+HOOD+PATCHES', true, false, date '2017-07-13', 'SANTHANA'),
  ('SLEEVE+NECK BINDING', 'SLEEVE+NECK BINDING', true, false, date '2021-12-30', 'MUTHURAJ'),
  ('SLEEVE+NECK PIPING', 'SLEEVE+NECK PIPING', true, false, date '2017-08-12', 'raju'),
  ('SLEEVE+NECK PIPING+NECK SEERI', 'SLEEVE+NECK PIPING+NECK SEERI', true, false, date '2017-08-12', 'raju'),
  ('SLEEVE+PLACKET+NECK TAPE', 'SLEEVE+PLACKET+NECK TAPE', true, false, date '2023-09-25', 'santhosh'),
  ('SLEEVE1', 'SLEEVE1', true, false, date '2020-08-01', 'Selvan'),
  ('SLEEVE2', 'SLEEVE2', true, false, date '2020-08-01', 'Selvan'),
  ('sleeve-left', 'sleeve-left', true, false, null, null),
  ('SLEEVE-PART/1', 'SLEEVE-PART/1', true, false, date '2021-06-23', 'admin'),
  ('SLEEVE-PART/2', 'SLEEVE-PART/2', true, false, date '2021-06-23', 'admin'),
  ('SLEEVE-PART/3', 'SLEEVE-PART/3', true, false, date '2021-06-23', 'admin'),
  ('SLEEVE-PART/4', 'SLEEVE-PART/4', true, false, date '2021-06-23', 'admin'),
  ('SLEEVE-PART/5', 'SLEEVE-PART/5', true, false, date '2021-06-23', 'admin'),
  ('sleeve-right', 'sleeve-right', true, false, null, null),
  ('SLV CUT&SEW PANEL', 'SLV CUT&SEW PANEL', true, false, date '2019-05-27', 'edp'),
  ('SMOCKING', 'SMOCKING', true, false, null, null),
  ('SMOKING', 'SMOKING', true, false, null, null),
  ('snood', 'snood', true, false, null, null),
  ('stickoff', 'stickoff', true, false, null, null),
  ('STRAP', 'STRAP', true, false, date '2017-07-29', 'SANTHANA'),
  ('STRAP 2', 'STRAP 2', true, false, date '2017-09-14', 'raju'),
  ('strickoff bit', 'strickoff bit', true, false, null, null),
  ('strike off', 'strike off', true, false, null, null),
  ('STRIKE OFF BITS', 'STRIKE OFF BITS', true, false, null, null),
  ('STRIKE OFF-BITS', 'STRIKE OFF-BITS', true, false, null, null),
  ('STRIKEOFF-BITS', 'STRIKEOFF-BITS', true, false, null, null),
  ('thocka', 'thocka', true, false, null, null),
  ('TIE', 'TIE', true, false, date '2016-08-05', 'RAJU'),
  ('TIP DYE', 'TIP DYE', true, false, null, null),
  ('TOP', 'TOP', true, false, null, null),
  ('TOP + PANT', 'TOP + PANT', true, false, date '2017-07-26', 'SANTHANA'),
  ('TOP BITS', 'TOP BITS', true, false, null, null),
  ('TOP FRONT', 'TOP FRONT', true, false, date '2019-11-24', 'mohan'),
  ('TOP FRONT INNER', 'TOP FRONT INNER', true, false, date '2019-11-24', 'mohan'),
  ('TOP FRONT,BACK+SLEEVE PANEL', 'TOP FRONT,BACK+SLEEVE PANEL', true, false, date '2019-11-17', 'Selvan'),
  ('TOP FRONT+BACK+SLEEVE', 'TOP FRONT+BACK+SLEEVE', true, false, date '2019-11-17', 'Selvan'),
  ('TOP INNER', 'TOP INNER', true, false, date '2017-03-02', 'RAJU'),
  ('TOP INNER + SLEEVE 2', 'TOP INNER + SLEEVE 2', true, false, date '2017-09-30', 'raju'),
  ('TOPFRONTBODY+TOPBACKBODY+TOPSLVE+NECKTAP', 'TOP FRONT BODY+TOP BACK BODY+TOP SLEEVE+NECK TAPE', true, false, date '2019-08-10', 'Selvan'),
  ('UNDER PACKET', 'UNDER PACKET', true, false, date '2023-09-22', 'santhosh'),
  ('UNDER PACKET+NECK TAPE', 'UNDER PACKET+NECK TAPE', true, false, date '2023-09-22', 'santhosh'),
  ('UNDER PLACKET+NECK TAPE', 'UNDER PLACKET+NECK TAPE', true, false, date '2023-09-22', 'santhosh'),
  ('UPPER POCKET', 'UPPER POCKET', true, false, date '2025-07-02', 'DHANDAPANI'),
  ('Vintage wash', 'Vintage wash', true, false, null, null),
  ('WAIST BAND', 'WAIST BAND', true, false, date '2016-05-20', 'sakthivel'),
  ('WAIST BAND / 1', 'WAIST BAND / 1', true, false, date '2024-02-13', 'Theepan Raj'),
  ('WAIST BAND / 2', 'WAIST BAND / 2', true, false, date '2024-02-28', 'theepan raj'),
  ('WAIST BAND+BOTTOM CUFF', 'WAIST BAND+BOTTOM CUFF', true, false, date '2018-07-28', 'm.prabhu'),
  ('WAIST LOOP', 'WAIST LOOP', true, false, date '2019-11-24', 'mohan'),
  ('WAIST PANEL FRONT & BACK', 'WAIST PANEL FRONT & BACK', true, false, date '2018-07-26', 'SAKTHI'),
  ('WAIST ROPE', 'WAIST ROPE', true, false, date '2018-05-02', 'SAKTHI'),
  ('washing', 'washing', true, false, null, null),
  ('wasshing', 'wasshing', true, false, null, null),
  ('WINGS', 'WINGS', true, false, date '2017-12-21', 'Balaji'),
  ('YOCK', 'YOCK', true, false, date '2023-11-20', 'Rambabu'),
  ('YOCK+NECK FOLD', 'YOCK+NECK FOLD', true, false, date '2023-11-20', 'Rambabu'),
  ('YOKE', 'YOKE', true, false, date '2016-03-07', 'admin'),
  ('YOKE+NECK TAPE', 'YOKE+NECK TAPE', true, false, date '2023-09-19', 'santhosh'),
  ('ZIP INNER', 'ZIP INNER', true, false, date '2019-07-25', 'SAKTHI'),
  ('ZIPPER BINDING', 'ZIPPER BINDING', true, false, date '2023-11-10', 'santhosh'),
  ('ZIPPER INNER PANEL+FOLDING', 'ZIPPER INNER PANEL+FOLDING', true, false, date '2020-11-05', 'Selvan')
) as v(short_name, description, all_coordinates, blocked, created_at, created_by)
where not exists (
  select 1 from public.components c where c.short_name = v.short_name
);
