-- ============================================================================
-- 0682 · Break the lv_garment_order_amendments ↔ lv_order_budget_revisions loop
--
-- SYMPTOM (2026-10-05, production): Orders ▸ Order Entry and Orders ▸
-- Accessories Plan both show "This screen couldn't load". Server log:
--
--   Could not load garment orders: canceling statement due to statement timeout
--
-- with only THREE garment orders in the table. Counting one child table as an
-- authenticated user answers with the real error:
--
--   ERROR: stack depth limit exceeded
--   SQL function "lv_garment_order_amendments" → "lv_order_budget_revisions"
--   → "lv_garment_order_amendments" → "lv_order_budget_revisions" → …
--
-- CAUSE. 0680 generated one `lv_<table>(id)` predicate per table in the unit
-- tree, AND-ing a call for every "owner" foreign key. Two FKs point at each
-- other:
--
--   garment_order_amendments.re_amendment_id → order_budget_revisions
--   order_budget_revisions.garment_order_id  → garment_order_amendments
--
-- and both were taken as owner edges, so each predicate calls the other. On a
-- row where both links are set the recursion only ends at the stack limit; a
-- child grid of a few hundred rows burns the 8 s `authenticated` statement
-- timeout first. Every embed under a garment order runs through it, which is
-- why Order Entry (14 embeds) and Accessories Plan both died — and why the
-- 0681 `current_location()` rewrite looked guilty: it is merely what sits at
-- the bottom of each round of the loop.
--
-- FIX. A garment order's unit is its SALES ORDER's unit — that is the rule its
-- own policies have used since 0485 (`has_order_access(sales_order_id)`).
-- `re_amendment_id` names the revision entry the order is being worked under:
-- a reference, not an owner. So the order's predicate is restated as exactly
-- its own policy, and the revision keeps its (correct) edge up to the order.
-- The detection query below found this to be the ONLY cycle among the lv_*
-- functions; the check at the end refuses to commit if any cycle remains.
--
-- (This file first held a per-transaction cache for is_current_location();
-- it was never applied, and the measurements that found the loop showed the
-- per-call cost was not the problem, so it was replaced rather than shipped.)
-- ============================================================================

create or replace function public.lv_garment_order_amendments(p_id uuid)
returns boolean
language sql
stable
security definer
set search_path to ''
as $f$
  select p_id is null or exists (
    select 1 from public.garment_order_amendments x
    where x.id = p_id
      and public.has_order_access(x.sales_order_id)
  )
$f$;

comment on function public.lv_garment_order_amendments(uuid) is
  'Is this garment order in the current unit? Its SALES ORDER''s unit — the same rule as '
  'its own policies (has_order_access). Generated by 0680; 0682 dropped the re_amendment_id '
  'edge, which looped through lv_order_budget_revisions back to here.';

revoke all on function public.lv_garment_order_amendments(uuid) from public, anon;
grant execute on function public.lv_garment_order_amendments(uuid) to authenticated;

-- ==========================================================================
-- Verification — from the catalog: no lv_* function may reach itself.
-- ==========================================================================
do $$
declare v_cycles text;
begin
  with recursive e as (
    select f.proname::text as src, m[1] as dst
      from pg_proc f, regexp_matches(f.prosrc, 'public\.(lv_[a-z0-9_]+)\(', 'g') m
     where f.proname like 'lv\_%' and f.pronamespace = 'public'::regnamespace
       and m[1] <> f.proname
  ), walk(start, cur, path) as (
    select src, dst, array[src, dst] from e
    union all
    select w.start, e.dst, w.path || e.dst
      from walk w join e on e.src = w.cur
     where not e.dst = any(w.path[2:]) and array_length(w.path, 1) < 16
  )
  select string_agg(distinct array_to_string(path, ' → '), '; ')
    into v_cycles
    from walk where cur = start;

  if v_cycles is not null then
    raise exception '0682: lv_* predicates still form a cycle: %', v_cycles;
  end if;
  raise notice '0682: no cycle among the lv_* unit predicates';
end;
$$;
